### ISSUE TITLE
Wildcards + extglobs does not match file

### ISSUE THREAD

**Issue by robrichard** [micromatch/micromatch#100]
When combing wildcards + extglobs for file extensions, `micromatch` does not match files at the root of the wildcard. Using micromatch@3.0.4.

## Please describe the **minimum necessary steps** to reproduce this issue:
See example code. It appears that `minimatch` handles this case correctly but micromatch does not.

```js
const minimatch = require('minimatch');
const micromatch = require('micromatch');

const pattern = 'foo/MyDir/**/*.+(js|jsx)';
const file = 'foo/MyDir/MyFile.jsx';
console.log('minimatch matches?', minimatch(file, pattern)); // true
console.log('micromatch matches?', micromatch.isMatch(file, pattern)); // false
```

Both minimatch and micromatch will correctly match the file if the extglob is removed and the pattern is simplified to `'foo/MyDir/**/*.jsx`.

**Comment by jonschlinkert** [comment]
> It appears that minimatch handles this case correctly but micromatch does not.

Am I correct in assuming that you're using windows?

**Comment by robrichard** [comment]
This is on macOS.

I'm using this via `fast-glob` via `relay-compiler` where the glob is generated from command line arguments where the user can pass a list of file extensions: https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js#L73

**Comment by jonschlinkert** [comment]
> since it needs to be generic enough to support any kind of extension, e.g. .+(js|ts|es)

you can do `.{js,jsx,ts,es}`.

**Comment by robrichard** [comment]
@jonschlinkert were you able to find a fix for this?

**Comment by jonschlinkert** [comment]
Apologies! I've been wrapping up a project to pay the bills. I did work on this though and found what's causing it. I just need to do some unit tests and push it up. After tomorrow I will be able to catch up. I'll escalate this on my todo list, but I won't mind at all if you ping me again. thanks

**Comment by robrichard** [comment]
@jonschlinkert if you share what you have I'd be happy to write the tests and prepare a PR.

**Comment by fidian** [comment]
I also volunteer to assist, considering I'm hitting the same issue. If nothing else, I've got a test or two of my own I can run to validate that the changes work.

**Comment by jonschlinkert** [comment]
Thanks for your patience, and for offering to help. I should be able to work on this today. If you want to do a pr with failing unit tests that would be great. Probably in [test/exglobs.js](https://github.com/micromatch/micromatch/blob/master/test/extglobs.js).

**Comment by fidian** [comment]
Tests are created that cover all of the scenarios brought up in the three issues.

**Comment by fidian** [comment]
Is there anything I can do to help finish this off?

**Comment by jonschlinkert** [comment]
> Is there anything I can do to help finish this off?

I'm really sorry it's taking so long. I had an unusually busy past couple of weeks. I've been catching up since Friday, I'm pretty close to getting this done. 

One thing that might help is to establish with 100% certainty that the issue is caused by a combination of wildcards and extglobs, I haven't had a chance to run the patterns (sans wildcards) in [extglob](https://github.com/micromatch/extglob). I can do that, but if you want to tackle it first that would be great. thanks

**Comment by fidian** [comment]
Does this help?

```
#!/usr/bin/env node

function showGlob(glob) {
  var regex, regexString;

  regexString = extglob(glob);

  // Convert to RegExp object, which makes it easier for copy and paste
  // into www.regexplained.co.uk to visually see what's going on.
  regex = new RegExp(regexString);
  console.log(glob, '->', regex);
}

function testGlob(file, glob) {
  var match;

  match = extglob.isMatch(file, glob);
  console.log('isMatch(' + JSON.stringify(file) + ', ' + JSON.stringify(glob) + ')', '->', match);
}

var extglob;

extglob = require('.');

console.log('From bug #100, each of these should match.');
console.log('');
showGlob('foo/MyDir/**/*.+(js|jsx)');
testGlob('foo/MyDir/MyFile.jsx', 'foo/MyDir/**/*.+(js|jsx)');
console.log('');
showGlob('**/!(folder).txt');
testGlob('file.txt', '**/!(folder).txt');
console.log('');
showGlob('*/dir/**/!(folder).txt');
testGlob('a/dir/file.txt', '*/dir/**/!(folder).txt');

console.log('');
console.log('Looking at just foo/MyDir: http://tinyurl.com/ycj87tzz');
console.log('Probable problem: "**/" makes an expression that must match a directory.');
console.log('');
console.log('This is also from bug #100, but it looks like it could be a separate issue.');
showGlob('*/b/!(c).txt');
testGlob('a/b/cc.txt', '*/b/!(c).txt');
console.log('');
console.log('The negative lookahead for "c" appears to exclude "cc.txt" but it does not appear to be related to the wildcard issue. http://tinyurl.com/y9sp5en7');
```

Results in the following output.

```
From bug #100, each of these should match.

foo/MyDir/**/*.+(js|jsx) -> /foo\/MyDir\/.*?(?!\.).*?\/.*?\.(js|jsx)+/
isMatch("foo/MyDir/MyFile.jsx", "foo/MyDir/**/*.+(js|jsx)") -> false

**/!(folder).txt -> /(?!\.).*?(?!\.).*?\/(?:(?!(?:folder)).*?)\.txt/
isMatch("file.txt", "**/!(folder).txt") -> false

*/dir/**/!(folder).txt -> /(?!\.).*?\/dir\/.*?(?!\.).*?\/(?:(?!(?:folder)).*?)\.txt/
isMatch("a/dir/file.txt", "*/dir/**/!(folder).txt") -> false

Looking at just foo/MyDir: http://tinyurl.com/ycj87tzz
Probable problem: "**/" makes an expression that must match a directory.

This is also from bug #100, but it looks like it could be a separate issue.
*/b/!(c).txt -> /(?!\.).*?\/b\/(?:(?!(?:c)).*?)\.txt/
isMatch("a/b/cc.txt", "*/b/!(c).txt") -> false

The negative lookahead for "c" appears to exclude "cc.txt" but it does not appear to be related to the wildcard issue. http://tinyurl.com/y9sp5en7
```

**Comment by jonschlinkert** [comment]
> Does this help?

It might, thank you! I'm working on it this afternoon.
