### ISSUE TITLE
Why doesn't this match?

### ISSUE THREAD

**Issue by wong2** [micromatch/micromatch#101]
## Please describe the **minimum necessary steps** to reproduce this issue:

I'd like to match urls which doesn't contain `note` or `review` in path:

`mm.isMatch('douban.com/subject/123/', 'douban.com/**!(note|review)**')`

## What is happening (but shouldn't):

but it returns `false`

**Comment by jonschlinkert** [comment]
The syntax is wrong `**` must be preceded or followed by a slash to match multiple directories.

**Comment by wong2** [comment]
thanks @jonschlinkert

**Comment by jonschlinkert** [comment]
any time!
