### ISSUE TITLE
negation extglob not matching correctly with wildcard

### ISSUE THREAD

**Issue by fidian** [micromatch/micromatch#103]
```
> mm.isMatch("a/b/c.txt", "*/b/!(c).txt")
false
> mm.isMatch("a/b/cc.txt", "*/b/!(c).txt")
false
```

Why is the second one not matching?

**Comment by jonschlinkert** [comment]
going to mark this as a duplicate of https://github.com/micromatch/micromatch/issues/100

**Comment by jonschlinkert** [comment]
Sorry for the delay. These should be working now.  

related 

https://github.com/micromatch/nanomatch/commit/acde39356bc0708b2e26149e6c084ae505fb9021
