### ISSUE TITLE
Possible recursive pattern bug

### ISSUE THREAD

**Issue by trevordmiller** [micromatch/micromatch#106]
I'm not sure if this is a bug or me doing something wrong but I'm not getting any matches with `someDir/**/someDir/**/*.somefile`. For example, with these patterns (the green and orange are what I would expect for each pattern, but no matches are found):

![image](https://user-images.githubusercontent.com/5497885/30177740-f8dda016-93c3-11e7-91cb-bc914f6e1236.png)

Is my pattern incorrect or is this a bug?

**Comment by trevordmiller** [comment]
If it is relevant, I'm using Jest which uses micromatch for the globbing; the use cases are npm scripts like this:

```json
"test:unit": "NODE_ENV=unitTest jest 'src/**/utils/**/*.test.js'",
"test:ui": "NODE_ENV=uiTest jest 'src/**/components/**/*.test.js'",
```

Which give these errors:

```
Invalid testPattern src/**/utils/**/*.test.js supplied
```

```
Invalid testPattern src/**/components/**/*.test.js supplied
```

**Comment by doowb** [comment]
@trevordmiller that helps a lot. What OS are you running those on? (it looks like Mac, but just want to be sure)

**Comment by trevordmiller** [comment]
@doowb Yes it is mac. I was able to get this working using Jest regex:

**package.json**
```
"scripts": {
    "test:unit": "NODE_ENV=unitTest TZ=utc jest 'src\\/.*utils\\/\\w+\\/index\\.test\\.js'",
    "test:ui": "NODE_ENV=uiTest TZ=utc jest 'src\\/.*components\\/\\w+\\/index\\.test\\.js'",
},
```

**Comment by jonschlinkert** [comment]
hmm interesting, is it only failing on double extensions?

**Comment by doowb** [comment]
`jest` is using an older version of `micromatch`. I'm trying to update it and run the tests with the latest version.

**Comment by trevordmiller** [comment]
@jonschlinkert Correct.

**Comment by jonschlinkert** [comment]
Closing since this was resolved in current version of micromatch.

**Comment by trevordmiller** [comment]
@doowb Any idea when Jest will upgrade to `micromatch 3.0` with this fix?

**Comment by doowb** [comment]
I don't know. When I get a chance I can try to submit a PR if someone else doesn't first.
