### ISSUE TITLE
Unable to bundle micromatch@3 with rollup

### ISSUE THREAD

**Issue by SimenB** [micromatch/micromatch#107]
Jest uses micromatch 2. When attempting to upgrade to micromatch 3 the build for the browser fails since rollup is unable to bundle micromatch@3.

## Please describe the **minimum necessary steps** to reproduce this issue:
See https://github.com/SimenB/micromatch-rollup

## What is happening (but shouldn't):
Rollup fails to bundle micromatch.

```
[!] Error: Illegal reassignment to import 'commonjsHelpers'
node_modules/class-utils/utils.js (11:0)
 9: var utils = require$$0(commonjsHelpers.commonjsRequire);
10: var fn = commonjsHelpers.commonjsRequire;
11: commonjsHelpers.commonjsRequire = utils;
    ^
12:
13: /**
```

## What should be happening instead?
Rollup should succeed.

**Comment by jonschlinkert** [comment]
closing, please create an issue on `class-utils`. also, technically this is a rollup issue, but I don't mind helping to get it fixed.

**Comment by SimenB** [comment]
Sure: https://github.com/jonschlinkert/class-utils/issues/3

**Comment by SimenB** [comment]
Still doesn't work, it now fails with `use`.

```
[!] Error: Illegal reassignment to import 'commonjsHelpers'
node_modules/use/utils.js (9:0)
 7: var utils = require$$0(commonjsHelpers.commonjsRequire);
 8: var fn = commonjsHelpers.commonjsRequire;
 9: commonjsHelpers.commonjsRequire = utils; // eslint-disable-line
    ^
10:
11: /**

error Command failed with exit code 1.
```
