### ISSUE TITLE
Braced expansion match issue

### ISSUE THREAD

**Issue by sntran** [micromatch/micromatch#108]
## Please describe the **minimum necessary steps** to reproduce this issue:

```node.js
> const mm = require('micromatch');
> mm(['./css/critical/header.css'], './css/critical{.css,**/*.css}')
```

## What is happening (but shouldn't):

It returns an empty array.

Further more, running `mm.isMatch('./css/critical/header.css', './css/critical{.css,**/*.css}')` returns `false`.

## What should be happening instead?

It should return `['./css/critical/header.css']`, and `.isMatch` check above should return `true`.

**Comment by jonschlinkert** [comment]
Why not use `css/critical/**/*.css`? The brace pattern you used is confusing, it would match `css/critical.css`. 

Also, the leading `./` is probably causing a problem in the glob. Using `./` is only necessary for `require()`, everywhere else it's unnecessary.

**Comment by sntran** [comment]
> Why not use css/critical/**/*.css? The brace pattern you used is confusing, it would match css/critical.css.

Because that is my intention. I want to include both "css/critical.css" and all the CSS files under "css/critical".

The leading `./` is there because my glob is given by outside user, which is used to Bash and the like. I can check and remove it, but this is something `path` module already handles, so I did not give much thought.

**Comment by jonschlinkert** [comment]
> Because that is my intention.

Got it, thanks for clarifying. 

> removing the leading `./` returns correct results

Thanks for confirming, I'm going to close this issue and open a new one. I think that should be handled.
