### ISSUE TITLE
3.0.0 regressions?

### ISSUE THREAD

**Issue by chimurai** [micromatch/micromatch#109]
First of all, thanks for this awesome library.

Was upgrading some dependencies for https://github.com/chimurai/http-proxy-middleware and stumbled on some failing tests.

## Please describe the **minimum necessary steps** to reproduce this issue:

Some glob patterns behave differently between `2.3.11` and `3.1.0`

## What is happening (but shouldn't):
micromatch `3.1.0`

```javascript
let micromatch = require('micromatch')

micromatch('/some/path/to/a/media/file/picture.jpg', '/**.jpg')
// []

micromatch('/some/path/to/a/media/file/picture.jpg', '/**.*')
// []

```

## What should be happening instead?
micromatch `2.3.11`

```javascript
let micromatch = require('micromatch')

micromatch('/some/path/to/a/media/file/picture.jpg', '/**.jpg')
// [ '/some/path/to/a/media/file/picture.jpg' ]

micromatch('/some/path/to/a/media/file/picture.jpg', '/**.*')
// [ '/some/path/to/a/media/file/picture.jpg' ]
```

**Comment by jonschlinkert** [comment]
Your glob pattern is defined incorrectly. It should be `/**/*.jpg` instead of `/**.jpg`. 

Per bash specification, a globstar (`**`) is regarded as a single star (`*`) when it is followed or preceded by any character besides `/`.

**Comment by chimurai** [comment]
Ah thanks. Guess I'll update/remove the incorrect globs :)
