### ISSUE TITLE
Inconsistent behavior between makeRe and isMatch

### ISSUE THREAD

**Issue by greyepoxy** [micromatch/micromatch#110]
- micromatch: 3.1.0
___
## Please describe the **minimum necessary steps** to reproduce this issue:
I have this code:
```js
const testGlob = '**/*.js';

console.log(micromatch.isMatch('./something/file.js', testGlob));
console.log(micromatch.isMatch('something/file.js', testGlob));
console.log(micromatch.makeRe(testGlob).test('./something/file.js'));
console.log(micromatch.makeRe(testGlob).test('something/file.js'));
```

## What is happening (but shouldn't):
It results in the following console output
```
true
true
false
true
```

## What should be happening instead?
I expected
```
true
true
true
true
```
___

Debugging through the source looks like the difference in behavior is the result of [matcher calling unixify](https://github.com/micromatch/micromatch/blob/master/index.js#L501) which [strips the prefix](https://github.com/micromatch/micromatch/blob/master/lib/utils.js#L304) by default.
If I pass in `{ stripPrefix: false }` (btw this option is not [documented](https://github.com/micromatch/micromatch#options))
```js
console.log(micromatch.isMatch('./something/file.js', testGlob, {stripPrefix: false}));
```
It results in `false` just like the direct regex comparison.

Unfortunately, in my situation I really need a regex that will match against paths starting with `./`. I am trying to convert the [webpack require-context](https://webpack.js.org/guides/dependency-management/#require-context) api into accepting a glob (it takes a regex). The strings it tests against that regex are always relative file paths that start with `./` and I cannot strip this prefix with their available api.

I tried fixing it by appending `./` to the front of the glob but
```js
console.log(micromatch.makeRe('**/*.js').toString());
console.log(micromatch.makeRe('./**/*.js').toString());
```
return the same regex
`/^(?:(^(?=.)|(?=.)(?!\.)(?:(?!(?:\/|^)\.).)*?\/)(?!\.)(?=.)[^\/]*?\.js(?:\/|$))$/`

**Comment by es128** [comment]
Related: https://github.com/micromatch/nanomatch/issues/6

**Comment by jonschlinkert** [comment]
Ah, this helped me narrow down exactly what's causing the issue. I think the `./` is sliced from the string before creating the regex, I'll get a fix pushed up. thanks

**Comment by greyepoxy** [comment]
thanks that worked!
