### ISSUE TITLE
inconsistencies between makeRe and isMatch with globs starting with './'

### ISSUE THREAD

**Issue by greyepoxy** [micromatch/micromatch#111]
- micromatch: 3.1.4
___
## Please describe the **minimum necessary steps** to reproduce this issue:
I have this code:
```js
const testGlob = './something/*.js';

console.log(micromatch.isMatch('./something/file.js', testGlob));
console.log(micromatch.makeRe(testGlob).test('./something/file.js'));
```

## What is happening (but shouldn't):
It results in the following console output
```
true
false
```

## What should be happening instead?
I expected
```
true
true
```

**Comment by jonschlinkert** [comment]
What OS and version of node.js are you using?

**Comment by greyepoxy** [comment]
Ah looks like you already have a fix but to answer your question,
`node -v` -> v8.9.1
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393

**Comment by greyepoxy** [comment]
Thanks for fixing! I verified that it works as expected
