### ISSUE TITLE
document behavior for ignore when using micromatch.isMatch

### ISSUE THREAD

**Issue by rprieto** [micromatch/micromatch#112]
Hi,

I just found this inconsistency between `match` and `isMatch` in `micromatch@3.1.4` and wondering if there's a functional difference I don't understand:

```js
const m = require('micromatch')
const IGNORE_BAD = { ignore: ['**/bad/**'] }

m.match('good/file.txt', '**/**', IGNORE_BAD)     // [ 'good/file.txt' ]
m.match('bad/file.txt', '**/**', IGNORE_BAD)      // []

m.isMatch('good/file.txt', '**/**', IGNORE_BAD)   // true
m.isMatch('bad/file.txt', '**/**', IGNORE_BAD)    // true
```

**Comment by jonschlinkert** [comment]
`options.ignore` isn't supported with `.isMatch`, since `.isMatch` can only take one string. Can you tell me more about the use case? I assumed there was no need for `ignore` with `.isMatch`, but it might make more sense if you tell me how you're using it.

**Comment by rprieto** [comment]
Thanks I didn't realise that. The best way is to show some code: https://github.com/thumbsup/thumbsup/blob/master/src/components/index/glob.js#L29

The use case is checking if a folder path matches a particular condition (doesn't start with a dot, and doesn't match particular regexes). I'm only testing one folder at a time so I only need a boolean. I ended up using `micromatch.match(...).length > 0`, but thought `micro.isMatch(...)` would be more obvious.

**Comment by rprieto** [comment]
I noticed the `ignore` option is also ignored for `.any(str, patterns, options)`. Does the mean the option is only valid for the basic `.match()` usage? What is the reason behind it?

In the meantime I'm using `mm.any(str, whitelist) && ! mm.any(str, blacklist)` which I hope is just as efficient.
