### ISSUE TITLE
initialization performance degraded

### ISSUE THREAD

**Issue by jonschlinkert** [micromatch/micromatch#125]
When 3.0 was published, I remember init time being in the 30ms range, because I wasn't happy about it. It's the reason I've been refactoring snapdragon, so I can remove deps anywhere possible and reduce init time.

However, it has come to my attention from https://github.com/mrmlnc/fast-glob/issues/92 that init time is 90ms! Which means that either I am remembering incorrectly, or something has changed - perhaps a huge dev dep accidentally got added to deps somewhere? (note that the benchmarks in this library test function calls not initialization of module dependencies).

In any case, this has now become a massive priority. I'm going to expedite the release of the next version with the following primary goal: fast initialization over modularization. That is the tradeoff that has to be made, and I'm fine with it. 

Please feel free to add constructive comments. 

related https://github.com/mrmlnc/fast-glob/issues/92#issuecomment-379553237

I think source maps are causing a big chunk of the init hit. They will be externalized in the next release.

**Comment by wtgtybhertgeghgtwtg** [comment]
I curious as to how https://github.com/micromatch/micromatch/issues/122 will affect this.  Are there any numbers on the start-up performance of `nanomatch` or `expand-brackets`?

**Comment by jonschlinkert** [comment]
Not any formal numbers, but it shouldn't have as much impact, or a negative impact, on the individual libraries. It's the build-up of different versions - along with extremely slow init in the source map libs, that's causing micromatch to initialize slowly.

That said, even if it has a negative impact it won't be for long. I'm actively working on the next versions to ensure init is as fast as possible. I also want to reduce deps dramatically.

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm betting it'll help performance.  While the latest version of `snapdragon` still has a good deal of duplication among transitive dependencies, the dependency tree of the version that `micromatch` currently pulls in is almost twice its size.

**Comment by wintercounter** [comment]
For me on Windows 10, Node 10.8 it's over 300ms.
