### ISSUE TITLE
Any bug with micromatch@2.3.11 ?

### ISSUE THREAD

**Issue by xwenliang** [micromatch/micromatch#126]
## Please describe the **minimum necessary steps** to reproduce this issue:

I want to math some urls without `/js/`, but I get confused by the two version:

## What is happening (but shouldn't):

```javascript
//micromatch@2.3.11
var mm = require('micromatch');
mm('a/b/js/c/d.js', '!(**/js/**)'); // ['a/b/js/c/d.js']
mm('a/b/js/c/d.js', '**/js/**'); // ['a/b/js/c/d.js']
```

## What should be happening instead?

```javascript
//micromatch@3.1.10
var mm = require('micromatch');
mm('a/b/js/c/d.js', '!(**/js/**)'); // []
mm('a/b/js/c/d.js', '**/js/**'); // ['a/b/js/c/d.js']
```

**Comment by jonschlinkert** [comment]
The latest version of micromatch in your example is correct.
