### ISSUE TITLE
Matcher doesn't work properly when glob contains Japanese characters.

### ISSUE THREAD

**Issue by sttk** [micromatch/micromatch#127]
## Please describe the **minimum necessary steps** to reproduce this issue:

```js
const { matcher } = require('micromatch')
matcher('folder/**/*')('folder/aaa.js') // => true
matcher('フォルダ/**/*')('フォルダ/aaa.js') // => false
```

## What is happening (but shouldn't):

See [gulp#2153](https://github.com/gulpjs/gulp/issues/2153).

## What should be happening instead?

Support glob which contains Japanese characters.

**Comment by jonschlinkert** [comment]
Where does gulp use micromatch? 

- what operating system? 
- are the characters valid file path characters?

**Comment by sttk** [comment]
@jonschlinkert I reproduced on macOS and this Japanese folder name is valid on it.

**Comment by jonschlinkert** [comment]
Ok, thanks. But again, where does gulp use micromatch?

**Comment by mrmlnc** [comment]
Inside `chokidar` package (see related issue).

**Comment by sttk** [comment]
@jonschlinkert Oh, sorry. I overlooked your one question.

Dependency is `gulp` -> `chokidar` -> `anymatch` -> `micromatch`.

**Comment by jonschlinkert** [comment]
Ok, thanks. I just wanted to clarify it's not a gulp issue. It seems like a relatively easy fix, I'll get something pushed up.

**Comment by phated** [comment]
@sttk ❤️for digging into the dependency chains and finding this!
@jonschlinkert ❤️for working on a fix!

**Comment by jonschlinkert** [comment]
@sttk does it work when you escape the characters?

Like:

```js
matcher('\フ\ォ\ル\ダ/**/*')('フォルダ/aaa.js')
```

**Comment by sttk** [comment]
@jonschlinkert No, it does not work well.

Maybe the part of the cause is `\b` in the following regular expression created by micromatch.

```js
/^(?:(?:\.[\\\/](?=.))?フォルダ[\\\/]?\b(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/](?!\.)(?=.)[^\\\/]*?(?:[\\\/]|$))$/
                                    ^^^
```

According to [this article in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), `\b` treats characters which is not specific set as a word break, including Japanese characters.

> Note: JavaScript's regular expression engine defines a specific set of characters to be "word" characters. Any character not in that set is considered a word break. This set of characters is fairly limited: it consists solely of the Roman alphabet in both upper- and lower-case, decimal digits, and the underscore character. Accented characters, such as "é" or "ü" are, unfortunately, treated as word breaks.

**Comment by jonschlinkert** [comment]
Good thinking! I was thinking there might be a check somewhere that uses `\w` to test some part of the glob, which would also probably fail for the same reason stated in the article you linked to. 

Now I have a couple of things to look for, thanks!

**Comment by jonschlinkert** [comment]
I have a fix for this. I'll push it up asap.

**Comment by phated** [comment]
Any update on this?

**Comment by MasatoMakino** [comment]
I found a `?\b` segment in [nanomatch](https://github.com/micromatch/nanomatch)

https://github.com/micromatch/nanomatch/blob/a983ca01207f0e01a5ef5368aa9bd60e882135e9/lib/compilers.js#L220

Dependency is `gulp` -> `chokidar` -> `anymatch` -> `micromatch` -> `nanomatch`.
nanomatch is used in [micromatch.makeRe()](https://github.com/micromatch/micromatch/blob/10aacd747e9bfe3cef5b2132b085dd8f34be1582/index.js#L571).

I tried to comment out '\b' segment.

```js
      if (prev.type === 'slash' && next.type === 'slash') {
        if (before.type === 'text') {
          this.output += '?';

          // if (after.type !== 'text') {
          //   this.output += '\\b';
          // }
        }
      }
```

```js
const { mm } = require('micromatch')
console.log(mm.isMatch('folder/aaa.js','folder/**/*'));
// => true
console.log(mm.makeRe('フォルダ/**/*'));
// => /^(?:(?:\.[\\\/](?=.))?フォルダ[\\\/]?(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/](?!\.)(?=.)[^\\\/]*?(?:[\\\/]|$))$/
console.log(mm.isMatch('フォルダ/aaa.js','フォルダ/**/*'));
// => true
```

However, it is not pass a test.

```md
  36221 passing (8s)
  1 failing

  1) globstars should support globstars (**):

      AssertionError [ERR_ASSERTION]: a/**/*
      + expected - actual

         "a/c"
         "a/x"
         "a/x/y"
         "a/x/y/z"
      -  "aa/a"
      -  "aaa/a"
      -  "aab/a"
       ]
      
      at module.exports (test/support/match.js:20:10)
      at Context.<anonymous> (test/globstars.js:22:5)
```
Does anyone have an idea?

**Comment by jonschlinkert** [comment]
I've fixed this and will be pushing up the next version of micromatch asap. I'm just getting docs finished.

**Comment by phated** [comment]
@jonschlinkert you are awesome!  That's in the 3.x release line, correct? That's the transitive dependency in gulp (-> chokidar -> anymatch -> minimatch).  It'd have to fall in the 3.x line because I believe chokidar is planning to remove older node support in their next released version.

**Comment by jonschlinkert** [comment]
Well, no, it's in the 4.0 release. Maybe I'm not so awesome... However, I can back and do a patch for the earlier versions as well.

**Comment by phated** [comment]
A back-ported patch would be greatly appreciated!

**Comment by sttk** [comment]
@jonschlinkert This issue is indeed fixed in the 4.0. Thanks!

**Comment by phated** [comment]
@jonschlinkert are we able to receive a backported patch?  With the changes to chokidar, it seems that gulp will be on an older version for awhile.

**Comment by jonschlinkert** [comment]
> are we able to receive a backported patch? With the changes to chokidar, it seems that gulp will be on an older version for awhile.

No, this is one of the reasons I had to refactor the parser.

**Comment by phated** [comment]
@jonschlinkert oh, okay. Thanks 😸
