### ISSUE TITLE
Confused about regex groups

### ISSUE THREAD

**Issue by milesj** [micromatch/micromatch#129]
## Please describe the **minimum necessary steps** to reproduce this issue:

```
mm.isMatch('bar', '(foo|bar)'); // false
mm.isMatch('baz', 'b(oo|az)'); // false
```

Using v3.1.10.

## What is happening (but shouldn't):

Returns false. I've tried `+()`, `@()`, and other variants with no luck.

## What should be happening instead?

I believe these should return true. 

```
'bar'.match('(foo|bar)'); // bar, bar
'baz'.match('b(oo|az)'); // baz, az
```

**Comment by jonschlinkert** [comment]
Not able to reproduce. Here is what I get:

```js
console.log(mm.isMatch('bar', '(foo|bar)')); // true
console.log(mm.isMatch('baz', 'b(oo|az)')); // true
```

- What OS are you using? 
- What version of node.js?
- any other details that might help figure out the issue

**Comment by milesj** [comment]
So I figured out the example in my first post. Turns out Jest was showing the wrong line numbers. However, this pattern is still confusing me.

```
    console.log packages/core/src/utils/isPatternMatch.ts:19
      foo a(r|z) false
    console.log packages/core/src/utils/isPatternMatch.ts:19
      bar a(r|z) false
    console.log packages/core/src/utils/isPatternMatch.ts:19
      baz a(r|z) false
```

Is it a whole word vs partial thing?

**Comment by milesj** [comment]
Here's the build: https://travis-ci.org/milesj/beemo/jobs/379067388

And the test: https://github.com/milesj/beemo/blob/master/packages/core/tests/SyncDotfilesRoutine.test.js#L75

And the code: https://github.com/milesj/beemo/blob/master/packages/core/src/SyncDotfilesRoutine.ts#L58

**Comment by milesj** [comment]
@jonschlinkert I don't see that documented anywhere. Is it new?

**Comment by jonschlinkert** [comment]
No.

**Comment by milesj** [comment]
`contains` worked for me, thank you!
