### ISSUE TITLE
Incorrect behaviour for for patterns with underscore

### ISSUE THREAD

**Issue by eGavr** [micromatch/micromatch#135]
Hi!

I've met a bug using the latest version of micromatch (3.1.10).

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
require('anymatch')(['dir-{suffix1,suffix2}/**/_*.js'], 'dir-suffix1/f_.js');
```

## What is happening (but shouldn't):

The result is `true`.

## What should be happening instead?

I expect the result to be `false`.

Thanks

**Comment by jonschlinkert** [comment]
@eGavr ping

**Comment by jonschlinkert** [comment]
Closing since I cannot reproduce this in micromatch. 

```js
const mm = require('micromatch');
console.log(mm.any('dir-suffix1/f_.js', ['dir-{suffix1,suffix2}/**/_*.js'])); // false
```

Ping @es128, looks like this might be a bug in anymatch in case you want to look into it.
