### ISSUE TITLE
Throws opaque error when argument to .matcher's return value is not a string

### ISSUE THREAD

**Issue by markasoftware** [micromatch/micromatch#136]
## Please describe the **minimum necessary steps** to reproduce this issue:
1. `micromatch.toMatcher('he??o')(47)`
…

## What is happening (but shouldn't):
The error `TypeError: str.charAt is not a function` is thrown.
…

## What should be happening instead?
A human-readable error should be thrown, making clear that the argument must be a string, and what the type of the erroneous argument was.
…

**Comment by jonschlinkert** [comment]
That's a javascript error. IMHO that's pretty clear, we can add a type check.
