### ISSUE TITLE
v4.0

### ISSUE THREAD

**Issue by jonschlinkert** [micromatch/micromatch#137]
## v4.0 

**Goals for 4.0**

- Targeted for first week of September, 2018
- massive reduction in dependencies - no more snapdragon.
- Load time - currently around 1.5ms
- Fast first match - less than 5ms from a cold start 
- opt-in caching 

## v3.0 post-mortem

**What we did well in 3.0**

- accuracy 
- parity with bash (ignoring cases where certain bash/shell behavior doesn't make sense in node.js)
- in-memory performance

**What needs to be improved**

- number dependencies
- load time (first require call)
- "first match"

Thoughts on the approach I used in 3.0, what I liked about it, and what I didn't like... 

- I used [snapdragon](https://github.com/here-be/snapdragon) for parsing and compiling the regexes in 3.0. This was a double-edged sword in that it helped me discover better strategies for creating the regular expressions,  but on the other hand, it added bloat to micromatch that I don't want. 
- inherited parsers - micromatch 3.0 is built on top of other single-responsibility matching libraries: extglob, expand-brackets, braces, and nanomatch (which only does basic globs/wildcards). Each of those libraries attempts to follow the conventions and rules of the equivalent bash module. This was a fun idea, and it worked out pretty well. I was able to build specific parsing and compiling rules in each library, then use those libraries essentially as plugins in micromatch. In some ways, this patterns has also made it easier to fix bugs related to matching and syntax, since it's more clear when a specific rule is being broken in the equivalent bash module.
- when v3.0 was published, initialization time was around 20ms, and there were far fewer total dependencies in the tree. We started upgrading snapdragon in a couple of the single-responsibility matching libs that micromatch depends on, then we quickly realized that a couple of the libs (one was `braces` I think) would take more time to upgrade than we anticipated. I had to decide whether or not it was worthwhile spending time to make this upgrades versus a complete overhaul.  This is ultimately what made me strongly dislike the approach I took to "building up the matchers" in 3.0. It started out as a neat idea, and made it easier to get the accuracy I wanted, but it has the horrible side effect of multiplying dependencies when version mismatches happen.

**Comment by phated** [comment]
@jonschlinkert great post!  And I like the goals set forth for 4.0 ❤️

**Comment by jonschlinkert** [comment]
thanks @phated!

**Comment by jimmywarting** [comment]
> massive reduction in dependencies

You could reduce some more if you target node LTS versions meaning no more support for node < 6

**Comment by jonschlinkert** [comment]
> You could reduce some more if you target node LTS versions meaning no more support for node < 6

The goal is for micromatch v4.0 to only have two dependencies: one for brace expansion, and one for parsing globs and creating regular expressions. The latter won't have any dependencies of its own. The brace expansion library (`braces`) has other dependencies, but we will tackle that to reduce deps next.

**Comment by paulmillr** [comment]
Love it!

**Comment by jonschlinkert** [comment]
Nice! I’m almost finished moving to my new home, so probably in the next week. Is that soon enough? Honestly fwiw it’s probably ready to publish but I was planning on doing optimization first.

**Comment by paulmillr** [comment]
Yes sir. Please optimize first.

**Comment by SimenB** [comment]
@jonschlinkert any news here? 🙏

**Comment by jonschlinkert** [comment]
> @jonschlinkert any news here?

Yes! I've spent quite a bit of time on unit tests and optimization. I'll try to get something pushed up to a branch this weekend. Then we can all agree on whether it's ready to publish. 

Thanks for the ping!

**Comment by SimenB** [comment]
Awesome news! Looking forward to land this in Jest 24 🙂

**Comment by jonschlinkert** [comment]
Quick update. I ran into some issues last night trying to push up changes, I haven’t had time to investigate why yet, but I think I saw something about GitHub having problems. I’ll try again tonight or tomorrow.

**Comment by SimenB** [comment]
Yeah, GitHub has had a lot of issues for the last 20 hours (still ongoing, even though it's better https://status.github.com/messages)

**Comment by paulmillr** [comment]
@jonschlinkert sup

**Comment by paulmillr** [comment]
@jonschlinkert ping.

**Comment by jonschlinkert** [comment]
@paulmillr hey sorry I missed your last ping. I didn't forget, I've been porting tests. I'll just go ahead and push something up tonight for everyone to see.

**Comment by paulmillr** [comment]
Nice! Thank you!

**Comment by SimenB** [comment]
Sorry to nag, but any updates here? Is it possible to release and land optimizations later, perhaps? 🙂 Really excited about the direction here!

**Comment by jonschlinkert** [comment]
> Sorry to nag, but any updates here? Is it possible to release and land optimizations later, perhaps? 🙂 Really excited about the direction here!

No worries, thanks for the reminder. Will do, I'll get something published ASAP.

**Comment by jonschlinkert** [comment]
just wanted to mention that I haven't forgotten, I was stuck on a windows-related matching issue that I spent a great deal of time trying to figure out. Over the next few days, I'll finally have time to get this finished!

**Comment by SimenB** [comment]
Happy new years! 🎉 Any news on this?

**Comment by SimenB** [comment]
Jest 24 is out with micromatch v3 (so we upgraded from 2 to 3). From my understanding of the OP, we should be able to upgrade without it being a breaking change for consumers. Had to hack around the snapdragon dep for the browser builds though, so still looking forward to this 😀

**Comment by paulmillr** [comment]
@jonschlinkert hey Jon, thanks for your work — do you think we can get the release ball rolling in February? We want to release chokidar v3 without node-gyp and radically decrease its bundle size before next nodejs v8.x release. That would be really useful!

**Comment by jonschlinkert** [comment]
@paulmillr yes I think I can make that happen!

**Comment by SimenB** [comment]
Hey again! Sorry about the nagging, but the `require` time has been identified as a pretty severe performance regression in the latest version of Jest: #8032. What's the current status of v4?

**Comment by thymikee** [comment]
Is there anything we can help with to make it happen? 🙂

**Comment by jonschlinkert** [comment]
> Hey again! Sorry about the nagging

No worries! I don't mind, and I appreciate that you care and have been so patient. I've actually been working on this for the past several hours. I finally figured out how to get around this windows issue!! I'm going to keep working on this until it's released!

**Comment by SimenB** [comment]
Awesome news, thanks @jonschlinkert!

**Comment by jonschlinkert** [comment]
@SimenB I'm still working on it. Spent the last couple of days fixing a bug. I'll be pushing up something today, then I should be able to publish a beta. FWIW I know it seems like I'm probably not doing anything on this, but there was a bug that I had a really hard time figuring out for some reason. I ended up having to refactor the entire logic for stars and globstars. I finally have it working!

**Comment by SimenB** [comment]
Super exciting @jonschlinkert! Will there be anything you'd consider breaking changes in this release?

**Comment by jonschlinkert** [comment]
Alright, I really had every intention of pushing [this up](https://github.com/micromatch/picomatch/tree/dev) on Friday, and now I've spent the last several days on it. This ended up being such a pain to fix that I started from scratch to get rid of some code debt. I'm glad I did, it helped me figure out a great parsing strategy that made picomatch faster by 200-400%, _without caching_! All of the unit tests are now passing, and I'm updating the docs!

More importantly, the code is now much easier to maintain and understand, which means it will take me less time to fix bugs and make updates. I'll add a description of the parsing strategy to the readme. 

> Super exciting @jonschlinkert!

Thank you! I'm starting to think so too now that I refactored :) 

> Will there be anything you'd consider breaking changes in this release?

I'm going through commits and creating docs now. I'll have a better (more confident) answer for you once I get a little further. In the meantime, here is a preview of one of the new features that (IMHO) make this release worth the wait and really nice to use:

```js
const micromatch = require('micromatch');
const paths = [];

// custom function to modify each string before it's tested
const format = str => str.replace(/\\/g, '/').replace(/^\.\//, '');

// custom function that is called on each successful match
const onMatch = ({ pattern, regex, input, value }) => {
  // pattern - the original glob
  // regex - the regex created from the glob
  // input - the unmodified input string to be matched
  // value - the "formatted" input string to be returned
  console.log({ pattern, regex, input, value });
};

// custom function that is called on each string that matches an ignore pattern
const onIgnore = ({ pattern, regex, input, value }) => {
  console.log({ pattern, regex, input, value });
};

const options = { onMatch, onIgnore, format, ignore: ['*/baz'] };
const matches = micromatch(['foo\\bar', 'foo\\baz', './abc/xyz'], '**', options);
console.log(matches);
//=> ['foo/bar',  'abc/xyz']
```

...and here are a few of the benchmarks with _caching disabled_!

![image](https://user-images.githubusercontent.com/383994/54323094-120e0900-45ce-11e9-9ad8-4ce903c59e67.png)

**Comment by SimenB** [comment]
Woah, absolutely bonkers numbers on those benchmarks! Awesome job.

The `format` function looks really interesting as well, I wonder if that can help with the underlying issue in #142

**Comment by csvan** [comment]
@jonschlinkert amazing work, those numbers look fantastic!

**Comment by jonschlinkert** [comment]
> I wonder if that can help with the underlying issue in #142

Yes! That's exactly the kind of use case that I was hoping to address with `format`!

> amazing work, those numbers look fantastic!

Thank you! Much appreciated!

**Comment by paulmillr** [comment]
@jonschlinkert what's the plan for v4 in removing `braces`? Are we ditching them?

**Comment by jonschlinkert** [comment]
> what's the plan for v4 in removing `braces`? Are we ditching them?

No. Braces are supported.

**Comment by paulmillr** [comment]
@jonschlinkert I'm asking because `braces` is the module that brings the most complexity to chokidar and other libs. 3 megabytes — that's too much...

We seem to have a way of optimizing micromatch (v4.0), but nothing for braces.

**Comment by jonschlinkert** [comment]
> I'm asking because `braces` is the module that brings the most complexity to chokidar and other libs. 3 megabytes — that's too much...

I'm not sure how that was determined when micromatch v4.0 wasn't pushed up yet, but I'll look into it and see what we can do.

**Comment by paulmillr** [comment]
I determined that because we are rewriting micromatch to use picomatch instead of nanomatch — but the braces module is staying the same, apparently.

**Comment by jonschlinkert** [comment]
> but the braces module is staying the same, apparently.

It's being refactored. The main cause of the size is two things:

1. People doing pull requests to bump versions for no good reason, which caused duplicate dependencies in the tree
1. source maps, which will not be included in the next version of braces.

**Comment by paulmillr** [comment]
Please take a look here, i've reduced braces/snapdragon size twice in no time: https://github.com/here-be/snapdragon/pull/23

**Comment by paulmillr** [comment]
@jonschlinkert Please take a look here, i've reduced braces/snapdragon size twice in no time: https://github.com/here-be/snapdragon/pull/23

**Comment by jonschlinkert** [comment]
> Please take a look here, i've reduced braces/snapdragon size twice in no time

The snapdragon API changed a lot between the current version and the version that braces uses. I appreciate the PR, and I'll merge it in, but the amount of time it would take to update braces to use the newer API wouldn't be worth it. I'd rather just refactor braces completely to not use snapdragon.

**Comment by jonschlinkert** [comment]
@paulmillr  https://github.com/micromatch/braces/pull/24

It's fast as hell. we have that going for us, which is nice. 

Also wanted to mention that we can't use the same parsing strategy with braces as with other globs. It's a lot more complicated. We need a real parser with an AST that allows us to handle nested expressions correctly. Assuming we want to continue avoiding the DDoS issues that have plagued minimatch

**Comment by paulmillr** [comment]
@jonschlinkert that's pretty huge. Please release this before micromatch v4.

**Comment by jonschlinkert** [comment]
Alright, it's published! 

I'll be out of the office until this afternoon. If any regressions happen I can triage then. Any help from team members would be appreciated too!
