### ISSUE TITLE
Inaccurate comparison within a regular expression

### ISSUE THREAD

**Issue by mrmlnc** [micromatch/micromatch#140]
## Issue source

* https://github.com/mrmlnc/fast-glob/issues/138

## Description

The RegExp returns `true` for a string that does not match the pattern.

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
const mm = require('micromatch');

const res = mm('packages/foo-foo/package.json', '**/foo/**/package.json');

console.log(res); // [ 'packages/foo-foo/package.json' ]
```

```js
mm.makeRe('**/foo/**/package.json')

/^(?:(?:\.[\\\/](?=.))?(?:(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/])?foo[\\\/]?(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/]package\.json(?:[\\\/]|$))$/
```

## What is happening (but shouldn't):

The `micromatch` returns `[packages/foo-foo/package.json']`.

## What should be happening instead?

The `micromatch` returns `[]`, because `foo-foo` does not match to `**/foo/**/package.json`.

## Broken test

```js
  it.only('issue #140', function() {
    var fixtures = ['a/b/some/c.md', 'a/b/c.md', 'a/b-b/c.md', 'a/bb/c.md', 'a/bbc/c.md'];

    nm(fixtures, '**/b/**/c.md', ['a/b/c.md', 'a/b/some/c.md']);
  });
```

**Comment by jonschlinkert** [comment]
I wonder why that's slipping past. Thanks for creating the issue, I'll make sure this gets fixed.

**Comment by mrmlnc** [comment]
I think that is related to the following part of the RegExp:

```js
/foo[\\\/]?(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/]/
______^ (1)__________________________________^ (2)
```

If I remove the second part and remove `?` at first, everything works correctly.

```js
/^(?:(?:\.[\\\/](?=.))?(?:(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/])?foo[\\\/](?!\.)(?:(?!(?:[\\\/]|^)\.).)*?package\.json(?:[\\\/]|$))$/

packages/foo-foo/package.json // ❌

packages/foo/some/package.json // 👍
packages/foo/some/bar/package.json // 👍
packages/foo/package.json // 👍
```

**Comment by jonschlinkert** [comment]
> If I remove the second part and remove `?` at first, everything works correctly.

thanks for debugging! This will help

**Comment by jonschlinkert** [comment]
lol and now this tweet: https://twitter.com/jonschlinkert/status/1068534438764707841
