### ISSUE TITLE
A package that micromatch depends on has a security vulnerability

### ISSUE THREAD

**Issue by mattparkins** [micromatch/micromatch#145]
For me this vulnerability comes to light when using babel-cli which ultimately uses micrmatch which relies on braces:

Regular Expression Denial of Service
Package: braces
Patched in >=2.3.1
Dependency of babel-cli [dev]
Path babel-cli > chokidar > anymatch > micromatch > braces
More info: https://npmjs.com/advisories/786

**Comment by jonschlinkert** [comment]
Please read closed issues on both libraries before spamming new issues.
