### ISSUE TITLE
Upgrade braces (security vulnerability)

### ISSUE THREAD

**Issue by dcruceanu** [micromatch/micromatch#146]
When executing `npm install `,
I' m receiving security issues:  130 vulnerabilities require manual review.
Braces 2.3.1 has a security vulnerability.

I have ran `npm audit fix`, but that's not fixing anything (I suppose that's because is not finding any new version).

I see that in package.json we have "braces": "^2.3.1", but this should be upgrade it to 2.3.2

**Comment by jonschlinkert** [comment]
please read existing issues before spamming duplicates.
