### ISSUE TITLE
`yarn audit` failure caused by vulnerable version of `braces`

### ISSUE THREAD

**Issue by Glazy** [micromatch/micromatch#147]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

1. `yarn install micromatch`
2. `yarn audit`

## What is happening (but shouldn't):

<img width="814" alt="screen shot 2019-03-05 at 12 29 04" src="https://user-images.githubusercontent.com/8593744/53805545-53554780-3f42-11e9-93a3-2d8e348bb94c.png">

## What should be happening instead?

`yarn audit` should pass.

**Comment by jonschlinkert** [comment]
## Please stop creating spam

This issue has been answered and explained dozens of times on braces, micromatch, and other repositories. 

`braces` was fixed ages ago, within a day or two of the report being created (although it was never a "vulnerability" in the first place, but that's besides the point). 

**Any library that depends on braces will automatically get the patched version by simply reinstalling**. _If you are not getting the latest version, you are probably using a lockfile that is preventing semver from doing its job_.
