### ISSUE TITLE
match using basename fails on a trivial case

### ISSUE THREAD

**Issue by blatx** [micromatch/micromatch#152]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

    var mm = require('micromatch');
    console.log(mm.isMatch('a/b.js', 'b.js', { basename: true }));

## What is happening that shouldn't be?

Output: 

    false

## What should be happening instead?

Output:

    true

BTW. minimatch does work on the same data:

    var minimatch = require('minimatch');
    console.log(minimatch('a/b.js', 'b.js', { matchBase: true }));

=>

    true

**Comment by jonschlinkert** [comment]
What OS are you using?
