### ISSUE TITLE
Missing any method

### ISSUE THREAD

**Issue by sebdeckers** [micromatch/micromatch#153]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

1. Install v3.1.10
1. Happily use micromatch.any in your app.
1. Upgrade to v4.10.1
1. ☠️ TypeError: micromatch.any is not a function

## What is happening that shouldn't be?

Method appears to be removed but I can't find mention in the docs.

## What should be happening instead?

Preserve the `.any()` method, if possible. Or make release notes with breaking changes more prominent.

**Comment by phated** [comment]
I don't recommend you bump major semver versions and not expect breaking changes (because that's what a major indicates).

**Comment by jonschlinkert** [comment]
> Preserve the `.any()` method, if possible. Or make release notes with breaking changes more prominent.

Sorry, it's not documented. I knew I'd miss something. 

`.isMatch` takes an array of patterns now, which be the same behavior is `.any`

**Comment by sebdeckers** [comment]
@jonschlinkert Thanks for the tip! 🙇🏼‍♂️ Would you like me to add an alias? Happy to do the PR for you. Also fine if this method is deprecated.

**Comment by jonschlinkert** [comment]
Yes, am I intended to create an alias and forgot. A pr would be great, thanks!

**Comment by jonschlinkert** [comment]
closing since this was fixed by https://github.com/micromatch/micromatch/pull/154. 

Thanks again @sebdeckers!
