### ISSUE TITLE
capture behaviour changed?

### ISSUE THREAD

**Issue by DrPizza** [micromatch/micromatch#155]
## Please describe the **minimum necessary steps** to reproduce this issue:
in micromatch 3.1.0:

```
> mm = require('micromatch');
{ [Function: micromatch]
...
}
> mm.capture('**/*.cpp', 'src/path/file.cpp');
[ 'src/path', 'file' ]
```

but in micromatch 4.0.1:

```
> mm = require('micromatch');
{ [Function: micromatch]
...
}
> mm.capture('**/*.cpp', 'src/path/file.cpp');
[ 'src/path' ]
```

## What is happening that shouldn't be?

capture isn't returning all captured parts.

## What should be happening instead?

capture should be returning all captured parts.

I mean it's possible that this is by design, but I don't see anything alluding to this in the changelog, so I'm assuming bug. If it's by design, how do I get the old behaviour?

Using node.js 11.13.0 or 11.14.0 on Windows.

**Comment by jonschlinkert** [comment]
It's a regression. 

Capture was added by PR in a previous release, and unfortunately, I never used it personally and wasn't as familiar with the expected results as I'd like to be. Which means test coverage failed me in this case. 

Thanks for creating the issue to let me know. Would you like to do a PR to add [test cases](https://github.com/micromatch/micromatch/blob/master/test/api.capture.js)?

**Comment by DrPizza** [comment]
I was just playing around with the options and I don't know if it's coincidental or by design, but setting `fastpaths: false` seems to reinstate the old behaviour.

**Comment by jonschlinkert** [comment]
> but setting `fastpaths: false` seems to reinstate the old behaviour.

Aha! That makes sense, and I think I know why. Thank you!

**Comment by DrPizza** [comment]
Glancing at the fastpathing, I suppose my testcase is rather inadequate. It happens that the existing test cases had patterns such as `test/**/*.js`, which doesn't look like it gets fastpathed. My case, however, is `**/*.cpp`, which I think does. The pre-cached fastpath patterns bake in whether or not capturing is enabled, which is why disabling fastpathing fixes things.

As such, a better set of test-cases would more or less double up every existing test, to include both fastpathed and non-fastpathed variants, to verify that fastpathing gets skipped if a particular option requires it. But I'm not sure if I have the energy to write tat many tests!

**Comment by jonschlinkert** [comment]
> I suppose my testcase is rather inadequate

IMHO your test was all that was needed. It tells me that the regex isn't being created properly when fastpaths are enabled. One easy solution is to automatically disable fastpaths when `capture` is enabled, but I'm going to try to fix the regex first.

**Comment by jonschlinkert** [comment]
Well, that was easy. [this line](https://github.com/micromatch/picomatch/blob/master/lib/parse.js#L116-L118) needs to be added to the fastpaths function, [right here](https://github.com/micromatch/picomatch/blob/master/lib/parse.js#L952). 

I can push this up, or you can do another PR with a code contribution if you want?

**Comment by DrPizza** [comment]
Well taking your word for it (it looks right!) that PR should do the job. It doesn't break anything at least.
