### ISSUE TITLE
Need help with windows paths

### ISSUE THREAD

**Issue by thasmo** [micromatch/micromatch#158]
`micromatch.makeRe('**/path/**', {windows: true})` returns this regular expression:
```js
^(?:(?:^|\/|(?:(?:(?!(?:^|[\\\/])\.).)*?)\/)path(?:\/(?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)|$))$
```
This [does not match](https://regex101.com/r/aGjAZh/1) a Windows path like `C:\Users\user\Projects\project\path\image.jpg`.

Afaik this [was fixed](https://github.com/micromatch/micromatch/issues/118) and worked properly in v3.

**Comment by thasmo** [comment]
It seems that some slashes in the glob string are not replaced by `[\\\/]` but by `\/`, which may be the problem.

**Comment by jonschlinkert** [comment]
Given that there are thousands of passing unit with Windows paths, I changed the title to something that makes more sense.

**Comment by jonschlinkert** [comment]
checking now

**Comment by jonschlinkert** [comment]
Also, I think it would make sense for me to add something like that to the regex in micromatch, so that this is done by default. It was never done this way before, but it makes sense.

**Comment by jonschlinkert** [comment]
Should be fixed. Thanks for reporting this issue!

**Comment by thasmo** [comment]
@jonschlinkert, thanks for fixing it that fast! Gonna try it in a bit.

**Comment by thasmo** [comment]
@jonschlinkert, the fix works for me. Thanks! :)
