### ISSUE TITLE
node_modules/micromatch/index.js:44

### ISSUE THREAD

**Issue by srikanth4b9** [micromatch/micromatch#159]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
SyntaxError: Unexpected token ...
error	at exports.runInThisContext (vm.js:53:16)
error	at Module._compile (module.js:387:25)
error	at Object.Module._extensions..js (module.js:422:10)
error	at Module.load (module.js:357:32)
error	at Function.Module._load (module.js:314:12)
error	at Module.require (module.js:367:17)
error	at require (internal/module.js:20:19)
…

## What is happening that shouldn't be?
SyntaxError: Unexpected token ...
ES6 code using in the file, its breaking build pipeline,
…

## What should be happening instead?
... syntax to be compatible to all version of JS, TS
…

**Comment by jonschlinkert** [comment]
Use an older version of micromatch.

**Comment by michaellenahan** [comment]
My suggestion is to revert to the latest 3.x version of micromatch ("3.1.10"), which does not make use of the "..." three-dots spread syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax in index.js

Compare:
https://github.com/micromatch/micromatch/blob/master/index.js
https://github.com/micromatch/micromatch/blob/3.1.10/index.js

**Comment by jayantraj13** [comment]
try downgrading your browser-sync
by npm i browser-sync@version
you can check version from https://www.npmjs.com/package/browser-sync

This solved my issue

**Comment by jerome25000** [comment]
Sorry, but I need to use node V6 (old projet) with grunt. I've installed grunt-cli 1.4.3 but I have the error wen running grunt

usr/lib/node_modules/grunt-cli/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);

I don't understand the link with browser-sync told by jayantraj13

How to solve this issue?

Thanks

**Comment by jayantraj1133** [comment]
> 
> 
> Sorry, but I need to use node V6 (old projet) with grunt. I've installed grunt-cli 1.4.3 but I have the error wen running grunt
> 
> usr/lib/node_modules/grunt-cli/node_modules/micromatch/index.js:44
> let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
> 
> I don't understand the link with browser-sync told by jayantraj13
> 
> How to solve this issue?
> 
> Thanks

my micromatch folder was in browser-sync in node module package and my error was showing
```  at Object.<anonymous> (/home/jayant/repo/jj/node_modules/browser-sync/dist/public/stream.js:3:18)```
so look where is your micromatch package try to downgrade that package or try to downgrade micromatch itself
https://www.npmjs.com/package/micromatch
