### ISSUE TITLE
Add node 6 end of support to changelog

### ISSUE THREAD

**Issue by yvele** [micromatch/micromatch#160]
You are now using object destructuring in micromatch v4 and that is not supported in node v6.

That's ok because you explicitly dropped support of node v6 https://github.com/micromatch/micromatch/commit/976d9569b96f84b386c35cfbbc0eb195a3f75e54#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

But it looks like you forgot to mention that in the breaking section of the changelog https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#400---2019-03-20

**Comment by jonschlinkert** [comment]
Thanks for pointing it out, would you like to do a PR?

**Comment by yvele** [comment]
Sure

**Comment by johnnyreilly** [comment]
If this could be added it would be helpful; I published a breaking changes version of ts-loader without meaning to. https://github.com/TypeStrong/ts-loader/issues/929

**Comment by jonschlinkert** [comment]
@johnnyreilly I'm really sorry that you experienced that. My apologies. 

@yvele thanks for the PR and issue!

closed by https://github.com/micromatch/micromatch/pull/161
