### ISSUE TITLE
Wrong match result

### ISSUE THREAD

**Issue by KnisterPeter** [micromatch/micromatch#172]
## Please describe the **minimum necessary steps** to reproduce this issue:

Run this in a node REPL:

```js
require('micromatch')(['/home/user/source/packages/folder-setup/src/index.ts'], '**/packages/folder/**/*.ts')
```

## What is happening that shouldn't be?

Theres a match which should not match.

```js
[ '/home/user/source/packages/folder-setup/src/index.ts' ]
```

## What should be happening instead?

```js
[  ]
```

**Comment by doowb** [comment]
Seems to work fine for me:

![image](https://user-images.githubusercontent.com/995160/60190609-f1766180-9800-11e9-828e-6bb9f386e696.png)

Maybe you can provide more information.

**Comment by jonschlinkert** [comment]
You have a typo. The path has `/folder-setup/` but your glob has `/folder/`

**Comment by KnisterPeter** [comment]
@jonschlinkert Sorry, not wanting to bother you. I've having the issue in `lint-staged` and not in the repl, but the repl is the minimal reproducing example for me.
I'll test against the latest version to make sure.

**Comment by KnisterPeter** [comment]
You are right, its the version, I'll open an issue at `lint-staged`. Thanks anyway.

**Comment by jonschlinkert** [comment]
Thanks for the update, and no worries. I appreciate the issue.
