### ISSUE TITLE
backport security updates to 3 branch

### ISSUE THREAD

**Issue by evilebottnawi** [micromatch/micromatch#174]
Sorry for removing issue template. Unfortunately, a vulnerability was found in `mixin-deep` package. It is possible to update all deps in `3` branch and do security release to avoid this problems?

It is very important for webpack users, webpack@4 support node@6 and we can't release webpack@5 (only node@8 supporting) right now so we can't update `micromatch` to `4` branch. 

To reproduce just install webpack and run `npm audit`, thanks. Any feedback will be great.

https://github.com/webpack/webpack/issues/9406

**Comment by jonschlinkert** [comment]
> Unfortunately, a vulnerability was found in `mixin-deep` package. It is possible to update all deps in `3` branch and do security release to avoid this problems?

`mixin-deep` was patched on all majors and should automatically be used without having to update any downstream dependencies. If you're not seeing the patch, then please delete lockfiles and `node_modules` then reinstall. If that doesn't work, please let me know.

**Comment by jonschlinkert** [comment]
I just installed webpack, and it is indeed showing vulnerabilities, but they have been patched and it shouldn't be reporting them as vulnerabilities anymore. I'll see what I can do. brb

**Comment by doowb** [comment]
I think this issue needs to be brought up with the npm security team since `mixin-deep@1.3.2` is patched with the fix and is the one that resolves through the dependency tree from webpack:

![image](https://user-images.githubusercontent.com/995160/61152219-cdc84200-a4b5-11e9-85e3-6f8b8eda9c33.png)

The [npm advisory](https://www.npmjs.com/advisories/1013) and the [snyk report](https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212) both show the correct version ranges.

**Comment by jonschlinkert** [comment]
FWIW, @doowb and I are both trying to figure this out. We're on it right now.

**Comment by jonschlinkert** [comment]
@evilebottnawi we have confirmed with Snyk that this is no longer a vulnerability. It appears that the error is with NPM. They should not be reporting this as a vulnerability anymore.

**Comment by doowb** [comment]
I ran `snyk test --dev` on a project where I installed `webpack` and here are the results:

![image](https://user-images.githubusercontent.com/995160/61153575-9eb3cf80-a4b9-11e9-8caf-581cf9b95e6e.png)

**Comment by evilebottnawi** [comment]
hm, it is bug in npm, right? With Snyk all is good, right?

**Comment by evilebottnawi** [comment]
npm audit:
```                                              
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
```

Thanks guys for feedback
