### ISSUE TITLE
Two digit range pattern doesn't work in 4.x.x

### ISSUE THREAD

**Issue by petrhajekomio** [micromatch/micromatch#180]
## Please describe the **minimum necessary steps** to reproduce this issue:
Just run `micromatch.isMatch('foo.bar53','foo.bar{53..55}');`
## What is happening that shouldn't be?
in `4.0.2` is above expression resulting in `false`.
## What should be happening instead?
Should result in `true`. In version `3.1.10` was working as expected.
## Additional info
In `4.0.2` range works just for single digit ranges (e.g. `micromatch.isMatch('foo.bar5','foo.bar{3..5}');`).

**Comment by jonschlinkert** [comment]
See: https://github.com/micromatch/micromatch#optionsexpandrange.

We'll probably be adding this natively soon, but for now you will need to use the approach described in the example.

**Comment by jonschlinkert** [comment]
Closing due to age
