### ISSUE TITLE
An explicitly specified dot leads to an incorrect pattern for glostar

### ISSUE THREAD

**Issue by mrmlnc** [micromatch/micromatch#181]
## Please describe the **minimum necessary steps** to reproduce this issue:

```js
const mm = require('micromatch');

const a = mm.makeRe('fixtures/{.,}*');
const b = mm.makeRe('fixtures/{.,}**');

console.dir(a, { colors: true });
// /^(?:fixtures[\\\/](\.|)[^\\\/]*?[\\\/]?)$/
console.dir(b, { colors: true });
// /^(?:fixtures[\\\/](\.|)[^\\\/]*?[\\\/]?)$/
```

## What is happening that shouldn't be?

The RegExp does not match `fixtures/second/nested/directory/file.md`.

## What should be happening instead?

Should match :)

**Comment by jonschlinkert** [comment]
That's correct. `**` must be the only thing in a directory segment, otherwise it's converted to `*`, per bash. 

Instead, it should be `{.*,*}` and `{**/.*,**}`

**Comment by mrmlnc** [comment]
Wow, I've never thought about it previously.

Sorry, but I cannot find any information about it. Can you recommend something?

// JFYI @sgtlambda

**Comment by jonschlinkert** [comment]
I remember reading it in the Bash code and/or docs and/or unit tests - that would be a good starting point, but I don't remember where it is specifically. FWIW [minimatch also follows this rule](https://github.com/isaacs/minimatch/blob/master/README.md#comparisons-to-other-fnmatchglob-implementations).

**Comment by mrmlnc** [comment]
Thanks! So, I think we can close this issue.
