### ISSUE TITLE
The `scan` method does not respect options

### ISSUE THREAD

**Issue by mrmlnc** [micromatch/micromatch#182]
Hi, @jonschlinkert,

> Think, that this rather question, not report bug or feature request.

The `micromatch` package has the `scan` method. This method takes a pattern and options.

> Scan a glob pattern to separate the pattern into segments.

As I understand it, this method can return an object saying whether a glob expression is in front of us or not. But this method does not respect my options.

The following example shows that my options (`noext: true`) are ignored. I assume pattern A is a glob expression and pattern B is not.

```js
const mm = require('micromatch');

const a = mm.scan('a/b/+(x|y)', { noext: false });
const b = mm.scan('a/b/+(x|y)', { noext: true });

console.log(a);
console.log(b);
```

Result:

```js
// a
{
  prefix: '',
  input: 'a/b/+(x|y)',
  base: 'a/b',
  glob: '+(x|y)',
  negated: false,
  isGlob: true // <------------ noext: true
}

// b
{
  prefix: '',
  input: 'a/b/+(x|y)',
  base: 'a/b',
  glob: '+(x|y)',
  negated: false,
  isGlob: true
}
```

Is this behavior correct? Should this method accept options? What about `nobrace` (it is not a part of picomatch from which we directly use the `scan` method)?

I ask this because I am looking for a configurable solution for https://github.com/mrmlnc/fast-glob/issues/105.

**Comment by jonschlinkert** [comment]
Hmm, that's a good question. I don't think I thought about whether nor not certain syntax features should be disabled when I wrote the code. 

I think this is a bug.

**Comment by M4rk9696** [comment]
Would the expected result be?

```
{
  prefix: '',
  input: 'a/b/+(x|y)',
  base: 'a/b+(x|y)',
  glob: '',
  negated: false,
  isGlob: false
}
```

I'll be happy to raise a PR for this if you can confirm this @jonschlinkert

**Comment by jonschlinkert** [comment]
I think so, yes. And similar results for other options like nonegate. A PR would be great!
