### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by ObsoleteAcey** [micromatch/micromatch#183]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
Build on any version of node < 8.6 in micromatch >= v4
…

## What is happening that shouldn't be?
There is a build error.  Object spread operators are not supported on node versions less than 8.6

https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread

https://node.green/#ES2018
…

## What should be happening instead?
No error during build from this library
…

**Comment by mrmlnc** [comment]
The `micromatch` packages since version 4 does require Node.js 8+.

https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#breaking-changes

**Comment by jonschlinkert** [comment]
> Most likely we need some words about it in the documentation or/and require Node.js 8.6+ in the `package.json` file.

Agreed, I'm good with whatever you want to do for this @mrmlnc.

**Comment by jonschlinkert** [comment]
closed by https://github.com/micromatch/micromatch/pull/184
