### ISSUE TITLE
`?(pattern)` doesn't work in 4.0.0 when if follows `+(pattern)`

### ISSUE THREAD

**Issue by pvdlg** [micromatch/micromatch#186]
##  **Minimum necessary steps** to reproduce this issue
```js
micromatch('ab', '+(a)?(b)')
=> [ 'ab' ] // this is expected

micromatch('aab', '+(a)?(b)')
=> [ 'aab' ] // this is expected

micromatch('aa', '+(a)?(b)');
=> [] // This should match

micromatch('a', '+(a)?(b)');
=> [] // This should match
```

## What is happening that shouldn't be?

`aa` or `a` doesn't match the glob `+(a)?(b)` while it should. It seems that micromatch ignore the fact that `?(b)` allows 0 match.

This was working in version 3 and is broken since version 4.

## What should be happening instead?

`aa` and `a` should match `+(a)?(b)` as it was the case in version 3.

**Comment by jonschlinkert** [comment]
Thanks for creating the issue. I fixed this locally, I'll push up a patch asap.

**Comment by pvdlg** [comment]
It appears to be fixed now. Maybe in picomatch@2.1.0? Not sure...
I think that can be closed unless the fix was unintentionnal and you want to keep that open to investigate.

**Comment by jonschlinkert** [comment]
> I think that can be closed unless the fix was unintentionnal and you want to keep that open to investigate.

Thanks for confirming! I fixed this in picomatch.
