### ISSUE TITLE
utils.isObject is not a function

### ISSUE THREAD

**Issue by glasseyes42** [micromatch/micromatch#187]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

https://github.com/micromatch/micromatch/blob/master/index.js#L231

This function doesn't exist...

## Please describe the **minimum necessary steps** to reproduce this issue:
Try using matchKeys

**Comment by MerlinDMC** [comment]
https://github.com/micromatch/picomatch/commit/cbc6d548965b19782eec3ba5b01e4a95612bff08 did remove the `isObject` function

**Comment by Bajix** [comment]
This breaks existing 4.0.1 installs. Please release a patch ASAP to fix this.

**Comment by jonschlinkert** [comment]
Ah, I broke this. I'll fix it ASAP today and push up a patch. Thanks for letting us know!

**Comment by Bajix** [comment]
These things happen; semantic versioning can be tricky sometimes. Thanks for being on top of this!

**Comment by jonschlinkert** [comment]
> semantic versioning can be tricky sometimes.

Thanks for understanding. In this case it's not really a versioning related thing. I made a coding mistake that would have broken the code no matter what version bump was made. We're getting it fixed right now. Thanks again.

**Comment by Bajix** [comment]
> Thanks for understanding. In this case it's not really a versioning related thing. I made a coding mistake that would have broken the code no matter what version bump was made. We're getting it fixed right now. Thanks again.

I see. I hadn't considered that there could've been issues in picomatch; I had just assumed isObject was intentionally removed and that micromatch accidentally broke due to both depending on a hidden export and due to the version issue. At face value, picomatch doing this and bumping minor sounds valid especially considering it's an internal export, and micromatch automatically updating by virtue of using `^2.0.7` instead of `~2.0.7` seems more problematic.

**Comment by jonschlinkert** [comment]
> and micromatch automatically updating by virtue of using `^2.0.7` instead of `~2.0.7` seems more problematic.

Yeah, and really, the fact that I used a utility from picomatch in micromatch is really the problem. I shouldn't have done that -- I only intended to use that utility during development, and I forgot to remove it before publishing micromatch. This was a fail on my part.

**Comment by doowb** [comment]
I published `picomatch@2.1.1` with the "reverted" change that removed `isObject`, however I think NPM is being slow because it's not installing `2.1.1` yet when I do `npm i picomatch@latest`.

When NPM catches up, this should be fixed. I'll check in a little bit and report back.

**Comment by doowb** [comment]
I logged into another machine and the correct version of `picomatch` was installed. For some reason `2.1.0` is still installing on my machine, even after clearing cache and trying `yarn`. Could someone else try and let me know if they have any issues?

**Comment by imagineimpact** [comment]
> I logged into another machine and the correct version of `picomatch` was installed. For some reason `2.1.0` is still installing on my machine, even after clearing cache and trying `yarn`. Could someone else try and let me know if they have any issues?

Try deleting node_modules & package-lock.json first.

**Comment by glasseyes42** [comment]
Thanks for taking care of this, will give it a test in the morning

**Comment by glasseyes42** [comment]
Seems fixed - thanks a lot
