### ISSUE TITLE
question of nonegate patterns

### ISSUE THREAD

**Issue by AlphaDu** [micromatch/micromatch#189]
## the result of '!' pattern is  different from my expectations:
I try these code below, the × mark is the result different from my expectation

```js
mm.isMatch('/aapi/test','/!(api)/**') //-> true √
mm.isMatch('/apii/test','/!(api)/**')  //-> true ×  
mm.isMatch('/apii/test','/!(api)/**')  //-> false √
```

is there bug cause the result 2 or some point of glob pattern I didn't know? please  disabuse me, thank you very much

 "micromatch": "^4.0.2",

**Comment by jonschlinkert** [comment]
the result is correct `api` does not match `apii`. Try:

```js
mm.isMatch('/apii/test','/!(api)*/**')
```

**Comment by AlphaDu** [comment]
> use `!/api/**` or `/api/**`

sorry, I try minimatch `mm('/apii/test', '/!(api)/**')` got true ,but micromatch `mm.isMatch('/apii/test', '/!(api)/**')` got false . so I think is there a bug ?

**Comment by jonschlinkert** [comment]
Minimatch is not a correct source of information. Please confirm your results with bash.

**Comment by AlphaDu** [comment]
> Minimatch is not a correct source of information. Please confirm your results with bash.

I search the doc and found that `!`  operator seem doesn't support in linux, and I compare with python glob,  nonegate operator has been deprecated~It confuse me.. maybe it's an operator I shouldn't use more. It's ambiguity in different context

**Comment by jonschlinkert** [comment]
Why aren't you using `!/api/**` or `/api/**`?

**Comment by AlphaDu** [comment]
> Why aren't you using `!/api/**` or `/api/**`?

because some history reason, except ./api/**, the other api is format like `/abc/api/**`, so I need distinguish backend api `/api/**` and `/abc/api/**` from all. no I'm using /!(api)/(!api)/**. but /apii/apii/test is wrong match.
