### ISSUE TITLE
posixSlashes: true does not work

### ISSUE THREAD

**Issue by tamuratak** [micromatch/micromatch#190]
## Please describe the **minimum necessary steps** to reproduce this issue:

1. execute `examples/option-onMatch.js`
```
$  node -v
v10.17.0
$  node option-onMatch.js 
{ input: 'some\\path', output: 'some\\path' }
{ input: 'some\\path', output: 'some\\path' }
{ input: 'some\\path', output: 'some\\path' }
```

## What is happening that shouldn't be?

Slashes in outputs are not converted.

## What should be happening instead?

Slashes in outputs should be converted to forward slashes.

**Comment by jonschlinkert** [comment]
Does `isMatch` return the correct result? Micromatch doesn't return file paths.

**Comment by tamuratak** [comment]
I don't understand what you are saying. What I am saying is that the outputs are different from ones in the comment in `examples/option-onMatch.js`.  Is the comment wrong?

```
$ cat option-onMatch.js 
'use strict';

const micromatch = require('..');

const onMatch = ({ glob, regex, input, output }) => {
  console.log({ input, output });
  // { input: 'some\\path', output: 'some/path' }
  // { input: 'some\\path', output: 'some/path' }
  // { input: 'some\\path', output: 'some/path' }
};

const isMatch = micromatch.matcher('**', { onMatch, posixSlashes: true });
isMatch('some\\path');
isMatch('some\\path');
isMatch('some\\path');
```

**Comment by jonschlinkert** [comment]
> Is the comment wrong?

Possibly. The examples were run on MacOS, it looks like you're on Windows. My question is whether or not `isMatch` returns the correct **`Boolean`** result, or if that is wrong as well. 

That said, I think that `posixSlashes` was renamed and I might have missed that in the docs. I believe it was mentioned in the changelog though. I'll look into this more as soon as I get a chance. Thanks for creating the issue.

**Comment by tamuratak** [comment]
I am on macOS.
OS: macOS High Sierra 10.13.6（17G9016）

```
$  cat option-onMatch.js
'use strict';
const micromatch = require('..');
const onMatch = ({ glob, regex, input, output }) => {
  console.log({ input, output });
};
const isMatch = micromatch.matcher('**', { onMatch, posixSlashes: true });
console.log(isMatch('some\\path'));
```

output
```
$  node option-onMatch.js
{ input: 'some\\path', output: 'some\\path' }
true
```

Thank you for you quick response. I hope this issue would help your development.

**Comment by jonschlinkert** [comment]
> Thank you for you quick response. 

you're very welcome! my pleasure

> I hope this issue would help your development.

Indeed it does! This at least lets me know that it's not a Windows issue. I'm pretty sure the option was renamed. Will confirm and report back ASAP.

**Comment by jonschlinkert** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.
