### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by guimard** [micromatch/micromatch#192]
Hi,

when launching test, "option.ignore" and "option.nonull" tests fail:

## Please describe the **minimum necessary steps** to reproduce this issue:

```
$ npm install
$ npm run test
...
  1951 passing (576ms)
  2 failing

  1) options
       options.ignore
         should filter out ignored patterns:

      AssertionError [ERR_ASSERTION]: [ 'a', 'b' ] deepEqual [ 'b' ]
      + expected - actual

       [
      -  "a"
         "b"
       ]
      
      at Context.it (test/options.js:31:14)

  2) options
       options.nonull
         should support the `nonull` option::

      AssertionError [ERR_ASSERTION]: [ '*', '\\*' ] deepEqual [ '*', '/*' ]
      + expected - actual

       [
         "*"
      -  "\\*"
      +  "/*"
       ]
      
      at Context.it (test/options.js:188:14)
```

**Comment by jonschlinkert** [comment]
Closing since this information is already provided by travis.

**Comment by guimard** [comment]
Hi,
I don't find any information related to this failure in .travis files

**Comment by jonschlinkert** [comment]
# README

![image](https://user-images.githubusercontent.com/383994/69593088-2bbd7800-0fc6-11ea-8e0b-b2f631cfe687.png)

# https://travis-ci.org/micromatch/micromatch

![image](https://user-images.githubusercontent.com/383994/69593124-42fc6580-0fc6-11ea-908c-ab93528c01cb.png)

**Comment by jonschlinkert** [comment]
With CI, it's generally not useful to create issues to notify the maintainers of a project that tests are failing, unless you're saying that different tests are failing than the ones failing on travis. In which case it would have been helpful if you had mentioned that in the OP.

**Comment by jonschlinkert** [comment]
(I accidentally just deleted a my previous comment, this is what it said) 

With CI, it's generally not useful to create issues to notify the maintainers of a project that tests are failing, unless you're saying that different tests are failing than the ones failing on travis. In which case it would have been helpful if you had mentioned that in the OP.

**Comment by guimard** [comment]
I simply tried to build it from source using `npm install && npm run test` _(I'm Debian Developer and try to update Debian package)_
