### ISSUE TITLE
Dot in path make globstars fail

### ISSUE THREAD

**Issue by vorfol** [micromatch/micromatch#193]
If the path has two dot-started folders the globstars won't work.

First three files are matched, but last is missed:
console.log(micromatch(['.vscode/a.js', '.vscode/test/null/b.js', 'any/.vscode/test/null/c.js', '.vscode/.test/d.js'], ['**/.vscode/**']));

** must match all kind of folders

**Comment by jonschlinkert** [comment]
> must match all kind of folders

Only if `dot` is true. https://github.com/micromatch/micromatch#options
