### ISSUE TITLE
Matching files under dot folder not working

### ISSUE THREAD

**Issue by tianhaoz95** [micromatch/micromatch#195]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
export function ignoreFiles(rawFiles: string[], ignoreList: string[]): string[] {
  const filteredFiles = micromatch(rawFiles, ignoreList);
  return filteredFiles;
}

test("test file ignore special cases", () => {
    const rawList: string[] = [
      "node_modules/README.md",
      "node_modules/@octokit/types/.github/ISSUE_TEMPLATE/04_thanks.md",
    ];
    const ignoreList: string[] = [
      "!node_modules/*",
      "!node_modules/**/*",
    ];
    expect(util.ignoreFiles(rawList, ignoreList)).not.toContain(
      "node_modules/@octokit/types/.github/ISSUE_TEMPLATE/04_thanks.md"
    )
};
```

…

## What is happening that shouldn't be?

`"node_modules/@octokit/types/.github/ISSUE_TEMPLATE/04_thanks.md"` is matched.

…

## What should be happening instead?

`"node_modules/@octokit/types/.github/ISSUE_TEMPLATE/04_thanks.md"` should be filtered and thus should not be contained in result, but it does.
…

**Comment by jonschlinkert** [comment]
Hi @tianhaoz95, thanks for creating the issue. 

Try passing `{ dot: true }` on the micromatch options. If that doesn't work I'd be happy to investigate further.

**Comment by tianhaoz95** [comment]
oh, that worked! thanks!

**Comment by jonschlinkert** [comment]
Great, sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.
