### ISSUE TITLE
update version of braces

### ISSUE THREAD

**Issue by automaticdreams** [micromatch/micromatch#198]
nom audit 
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ babel-cli [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ babel-cli > chokidar > anymatch > micromatch > braces        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by jonschlinkert** [comment]
# Please read: It's pinned!

![image](https://user-images.githubusercontent.com/383994/77780160-ed929c80-7029-11ea-9533-9dc5ad290b4b.png)
