### ISSUE TITLE
Update snapdragon to avoid deprecation warnings

### ISSUE THREAD

**Issue by polarathene** [micromatch/micromatch#204]
Please see https://github.com/here-be/snapdragon/issues/24

Gatsby uses `micromatch` and is throwing two warnings due to `snapdragon` needing to update semver and push out a new release.

**Comment by danez** [comment]
The linked issue has been resolved, and also micromatch does not use snapdragon anymore in the latest version.

**Comment by danmarshall** [comment]
Does version 4 have any breaking changes from version 3? I'd like to upgrade but not sure if the API is different.
