### ISSUE TITLE
Using matcher inside Array.filter doesn't work

### ISSUE THREAD

**Issue by XxSven** [micromatch/micromatch#206]
## Please describe the **minimum necessary steps** to reproduce this issue:
Use matcher inside Array.filter function
`['a','b','c'].filter(mm.matcher('b'));`
…

## What is happening that shouldn't be?
Array is not filtered
Result should be ['b']
…

## What should be happening instead?
Array should be filtered
Result is ['b', 'c']
…

Array.filter gives value and index as arguments, so it gives matcher function the index as returnedObject value
![image](https://user-images.githubusercontent.com/22731605/87136799-482fcb80-c29c-11ea-9194-414508e36396.png)

**Comment by jonschlinkert** [comment]
Do:

```js
const matcher = mm.matcher('b');
['a','b','c'].filter(input => matcher(input)));
```

**Comment by XxSven** [comment]
This is a good workaround but shouldn't it work as mm.filter that was deleted from previous versions ?

**Comment by jonschlinkert** [comment]
> This is a good workaround but shouldn't it work as mm.filter that was deleted from previous versions ?

No, there was no promise of parity with `.filter()`.

**Comment by jonschlinkert** [comment]
I should have clarified that this `['a','b','c'].filter(mm.matcher('b'));` is incorrect, since it's passing all of the arguments from the filter function to micromatch, including the index and entire array. Thus, the example is wrong.
