### ISSUE TITLE
Inconsistent behaviors between `/foo/bar/**` and `/foo/*/**`

### ISSUE THREAD

**Issue by vilicvane** [micromatch/micromatch#210]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

```ts
minimatch.isMatch('/foo/bar', '/foo/bar/**'); // true
minimatch.isMatch('/foo/bar', '/foo/*/**'); // false
```

I was expecting both result in `false` (or `true`, but I'd prefer `false`, and that's also the behavior of minimatch).

**Comment by jonschlinkert** [comment]
Those are both correct. `/foo/*/**` is explicitly saying that at least three segments are expected. If you want to match everything why add `/*/`? Instead just do `/foo/**`.
