### ISSUE TITLE
extglob Denial of service

### ISSUE THREAD

**Issue by Var-S1** [micromatch/micromatch#218]
Hello, catastrophic backtracking with `extglob`  

## **Minimum necessary steps** to reproduce this issue:
```
const mm = require("micromatch");
mm.isMatch('ababababababababababababababababababababababababababababababababababababababa','+(*(ab))');
```
## What is happening that shouldn't be?
catastrophic backtracking, blocking execution

Is there any way to prevent it from backtracking without removing `extglob` from the pattern or an evaluation timeout option?

**Comment by jonschlinkert** [comment]
The safest way to prevent users from defining malicious regular expressions is to disallow users from defining regular expressions.

**Comment by Var-S1** [comment]
Thank you for the quick response, looks like I have reconsider my applied methodology.

**Comment by conartist6** [comment]
You could trying using micromatch to turn an extglob into a regex and then executing it with [@iter-tools/regex](https://www.npmjs.com/package/@iter-tools/regex) which is non-backtracking.

**Comment by conartist6** [comment]
Oh oops it doesn't work quite yet because the compiled expression uses lookahead which I don't support yet.
