### ISSUE TITLE
Alternatives in extglobs not matching correctly?

### ISSUE THREAD

**Issue by rauschma** [micromatch/micromatch#235]
## Please describe the **minimum necessary steps** to reproduce this issue:

```js
const mm = require('micromatch');

mm.isMatch('file.html', '**/*.html'); // true (OK)
mm.isMatch('file.html', '@(**/*.html|**/*.md)'); // false (not OK, right?)
mm.isMatch('dir/file.html', '@(**/*.html|**/*.md)'); // true (OK)
```

**Comment by jonschlinkert** [comment]
@rauschma thanks for creating the issue. Have you tried moving the double stars outside of the extglobs, like one of the following?

```
**/@(*.html|*.md)
**/*@(.html|.md)
**/*.@(html|md)
``

I'm curious if those are also wrong. As I recall, matching with `**` is complicated inside extglobs due to contradictory conventions between bash and extglob, but also because we're limited to the capabilities of javascript's regex. At least we were more limited before lookbehinds were introduced. But I think we can safely start using those in this library now, so perhaps we'll be able to handle this more gracefully. 

Marking this as a bug. Until we get this patched, you should be able to use braces to accomplish the same thing in the meantime:

```
**/*.{html,md}
```

Let me know if this doesn't work for you and we can try to come up with something better.

**Comment by rauschma** [comment]
These all work.

Alas, my globs exist separately and I need to compose them.

I can work around the issue by looping over the alternatives and checking them individually. So it depends on whether you think anyone else might profit from this working.

**Comment by jonschlinkert** [comment]
Great to know, thanks for checking. Since you were able to get other syntaxes to work, I'll go ahead and close since there might be diminishing returns in solving it. thanks again for creating the issue. If you notice something isn't working the way you thought, feel free to reopen.

**Comment by jonschlinkert** [comment]
@rauschma btw I just noticed your name. I've read your blog lots of times, it's been very valuable and interesting. thanks for the awesome content over the years!

**Comment by rauschma** [comment]
@jonschlinkert Cool! Thanks for telling me.
