### ISSUE TITLE
micromatch('.prettierrc.json', '**/*.json') => false

### ISSUE THREAD

**Issue by AlekseiZhabitenko** [micromatch/micromatch#236]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
micromatch('.prettierrc.json', '**/*.json')
…

## What is happening that shouldn't be?
It returns `false`

…

## What should be happening instead?
It should return `true`
…

**Comment by jonschlinkert** [comment]
Hi @AlekseiZhabitenko, thanks for creating an issue. This is one of those things that I personally forget sometimes. Try passing the following [options](https://github.com/micromatch/micromatch#options) object as the last argument:

```js
micromatch('.prettierrc.json', '**/*.json', { dot: true })
```

Let me know if that doesn't work and we'll get it figured out.

**Comment by AlekseiZhabitenko** [comment]
> Hi @AlekseiZhabitenko, thanks for creating an issue. This is one of those things that I personally forget sometimes. Try passing the following [options](https://github.com/micromatch/micromatch#options) object as the last argument:
> 
> ```js
> micromatch('.prettierrc.json', '**/*.json', { dot: true })
> ```
> 
> Let me know if that doesn't work and we'll get it figured out.

Thanks. It's a bit strange behavior by default though.

**Comment by jonschlinkert** [comment]
np, glad you got it fixed.

> Thanks. It's a bit strange behavior by default though.

Fair enough. FWIW it's the convention that was already established by other glob matching libraries. My guess is that the convention is used because most file systems don't show dot files to users by default.
