### ISSUE TITLE
[BUG] Vulnerabilities Found in Micromatch and Braces

### ISSUE THREAD

**Issue by MarioTeixeiraCx** [micromatch/micromatch#240]
Hello,

I'm a security analyst with Checkmarx's CxResearch group, and I wanted to bring to your attention some vulnerabilities we've reported to your inbox since we haven't received any response.

We'd much prefer to address these concerns privately, so we're hoping you can suggest a way for us to do that.

We appreciate your attention to this matter.

Best regards,
Mário Teixeira

**Comment by jonschlinkert** [comment]
Here is our [security policy](https://github.com/micromatch/micromatch/security/policy). Please use the contact information on that document. Thank you, and I'll go ahead and close with the expectation that you will be getting in touch.

**Comment by MarioTeixeiraCx** [comment]
Hi @jonschlinkert, we have followed that document and contacted the email that is listed there. I opened this issue after we didn't get a response after 2 months.
