### ISSUE TITLE
What's the deal with 4.0.7?

### ISSUE THREAD

**Issue by jacobjmarks** [micromatch/micromatch#260]
Version 4.0.7 has been released from the [v4](https://github.com/micromatch/micromatch/tree/v4) branch where 4.0.6 was based on [master](https://github.com/micromatch/micromatch/tree/master). These branches have diverged and 4.0.7 looks to have regressed upwards of 9 commits that were released in 4.0.6.

**Comment by jpsla94** [comment]
Hello,

Any update?

**Comment by andreparacino** [comment]
Hi, 
Ay update on this yet?

**Comment by jpsla94** [comment]
Update?

**Comment by paulmillr** [comment]
No updates. Send pull requests instead of writing this here.

**Comment by jacobjmarks** [comment]
@paulmillr The purpose of this issue is to raise a discussion and bring to light what is seemingly a regression between 4.0.6 and 4.0.7; this is not something which can be resolved by some out-of-the-blue pull request and dismissing it as such with no context is not helpful to anyone. Do you have an explanation or further insights?

**Comment by paulmillr** [comment]
We've released 4.0.6. Then it was decided that 4.0.6 breaks things. So we wanted to push 4.0.7 reverting it and releasing 5.0 which breaks things.
