### ISSUE TITLE
micromatch 4.0.5 and braces 3.0.3

### ISSUE THREAD

**Issue by jolebowski** [micromatch/micromatch#261]
Hello,

I have micromatch 4.0.5 and braces 3.0.3. I updated through override of the dependencies. But the vulnerability appears on the security report.

The NPM package micromatch is vulnerable to Regular Expression Denial of Service (ReDoS). The vulnerability occurs in micromatch.braces() in index.js because the pattern .* will greedily match anything. This is a significant issue that can lead to performance degradation and potential denial of service.

Thank you for looking into this serious error.

**Comment by jonschlinkert** [comment]
duplicate. please review existing issues before creating new ones

**Comment by jolebowski** [comment]
It's true that it already exists, but the problem still hasn't been solved.

**Comment by jonschlinkert** [comment]
That's trolling.

**Comment by jolebowski** [comment]
I'm sorry, but I don't trolle when my project has a serious error that could be dangerous for the security of my site. 
Especially when I see that the problem has already been raised two months ago.
