### ISSUE TITLE
Globstar and Braces on slashes issues

### ISSUE THREAD

**Issue by FarhanMS123** [micromatch/micromatch#262]
## Please describe the **minimum necessary steps** to reproduce this issue:

I did following commands using `pnpx tsx`, and here function that I executed and output

```ts
let mm;
mm = (await import("micromatch")).default

mm.isMatch("test/page_name.page.tsx", "**.page.tsx"); // true
mm.isMatch("test/page_name.page.tsx", "**.page.{tsx,jsx}"); // false
mm.isMatch("test/page_name.page.tsx", "**.page.{tsx,jsx}", {basename:true}); // true
mm.isMatch("test/page_name.page.tsx", mm.braces("**.page.{tsx,jsx}")); // false
mm.isMatch("test/page_name.page.tsx", mm.braces("**.page.{tsx,jsx}"), {basename:true}); // true
mm.isMatch("test/page_name.page.tsx", mm.braces("**.page.{tsx,jsx}", {expand:true})); // true

mm.isMatch("test/page_name.page.tsx", "**.page.*"); // false
mm.isMatch("test/page_name.page.tsx", "**.page.*", {basename:true}); // true
mm.isMatch("test/page_name.page.tsx.html", "**.page.tsx.html"); // true
mm.isMatch("test/page_name.page.tsx.html", "**.page.*.html"); // false

mm.capture("**.page.*.html", "page-name.page.tsx.html"); // [ 'page-name', 'tsx' ]
mm.capture("**.page.*.html", "test/page-name.page.js.html"); // undefined
mm.capture("**.page.*.html", "test/page-name.page.js.html", {basename:true}); // undefined
mm.capture("**.page.js.html", "test/page-name.page.js.html", {basename:true}); // [ "test/page-name" ]
```

## What is happening that shouldn't be? What should be happening instead?

At first, I think this is braces problem, but after further testing, this also not working for globstar. I just wonder did this expected or not. In summarize, this following command is expected to return `true` and returning `true`.

```ts
mm.isMatch("test/page_name.page.tsx", "**.page.tsx"); // true
mm.isMatch("test/page_name.page.tsx", "**.page.*", {basename:true}); // true
```

But, some equivalent not working and instead return `false` rather than `true`.

```ts
mm.isMatch("test/page_name.page.tsx", "**.page.{tsx,jsx}"); // false
mm.isMatch("test/page_name.page.tsx", "**.page.*"); // false
```

Second, this code working

```ts
mm.capture("**.page.js.html", "test/page-name.page.js.html", {basename:true}); // [ "test/page-name" ]
```

But, the equal is not ...

```ts
mm.capture("**.page.*.html", "test/page-name.page.js.html", {basename:true}); // undefined
```

Does these intended?

**Comment by FarhanMS123** [comment]
I read many issues and somewhat related to 
- By search `braces` and `brace`: #262 #169 
- By search `globstar` open: #246 #244 #167 #169 
- By search `globstar` close: #113 #102 #100
- By search `slash`: #230 

Some how, I still figuring out does this is intended. I understand you all and these libraries (include pico) are created based on Bash Glob Match. But, I can't figuring out how to test it or is there any standardize document or RFC related to it.

**Comment by jonschlinkert** [comment]
Neither of these should be true, since `**` is equivalent to `*` when it's not the only thing in a path segment. 

```js
mm.isMatch("test/page_name.page.tsx", "**.page.{tsx,jsx}"); // false
mm.isMatch("test/page_name.page.tsx", "**.page.*"); // false
```

However...

```
// I think this one is wrong, and might be a bug. All of the instances you pointed to that might be wrong are probably related to this one. I'll look into this...
console.log(mm.isMatch("test/page_name.page.tsx", "**.page.tsx")); // true

// this one is correct
console.log(mm.isMatch("test/page_name.page.tsx", "**.page.*", { basename:true })); // true
```

**Comment by FarhanMS123** [comment]
Aah... So it is intended. Thankyou for your help. I'll try to find a work around. This issue can be close now.
