### ISSUE TITLE
enabling dotfiles changes behavior of **/ glob patterns

### ISSUE THREAD

**Issue by bcoe** [micromatch/micromatch#79]
when `dotfiles=false`, the following rule `**/foo.js` would match `foo.js`.
when `dotfiles=true`, the rule `**/foo.js` does not match `foo.js`.

I've worked around this in `nyc`, with the following logic:

https://github.com/istanbuljs/test-exclude/commit/43008d5f045b06898b11a3f47e310e8181e332ec

But I'd prefer to have less exclude rules.

**Comment by jonschlinkert** [comment]
thanks @bcoe there is a refactor here that supports this https://github.com/jonschlinkert/micromatch/tree/dev that has 7,000+ unit tests and a real parser-compiler (so it even creates an AST, not sure what that could be used for yet lol). 

I also just pushed up some unit tests to show that it's passing in the refactor (fwiw the refactor is ready to publish I just have to wrap up a commitment then finish docs before I publish. I can try to do that in the next couple of days)

**Comment by bcoe** [comment]
@jonschlinkert wow, you've been busy; One that lands, I'll happily help test against nyc's test cases.

**Comment by jonschlinkert** [comment]
> I'll happily help test against nyc's test cases

great! I'd be happy to add some here too if you want

**Comment by jonschlinkert** [comment]
related https://github.com/jonschlinkert/micromatch/blob/dev/test/options.js#L43-L44

@bcoe getting closer on the refactor.  I'm just working on docs and a couple of windows path-related bugs that cropped up on appveyor. I'll update with progress

**Comment by jonschlinkert** [comment]
I believe this is resolved in 3.0.0. please feel free to reopen if you or anyone else still experience this issue.
