### ISSUE TITLE
Get the captured/matched results?

### ISSUE THREAD

**Issue by fidian** [micromatch/micromatch#85]
My goal is to rename files using a syntax similar to `mmv`.  Here's an example of how to use that tool:

    mmv 'folder/*.jpg' 'other-destination/#1.jpeg`

In order to make my library, I would really like to capture the matches for the various patterns. Assuming a filename of "test/documentation/module-controller.md", I would expect the following:

    // [ "module-controller.md" ]
    console.log(match("test/documentation/*"))

    // [ "test/documentation", "module-controller" ]
    console.log(match("**/*.md"));

    // [ "documentation", "module", "md" ]
    console.log(match("test/(doc*|lib*)/!(xxxx)*-controller.*"));

Is it easily possible to make the generated regular expressions capture these groups? My goal would be to avoid forking the repository and working with a published API when possible. I can get the regular expression but I'm having difficulty detecting the groups and converting them to capture.

Do you see this as something that could be added to your library?

**Comment by jonschlinkert** [comment]
Once the [dev branch](https://github.com/jonschlinkert/micromatch/blob/dev/index.js#L573) is merged, you will be able to use the `.parse` method to get an AST (with optional sourcemap), which you can then use however you want. Your use case seems like an excellent example of what you can do with the AST.

Does that address what you're trying to accomplish? I can show you how to use the AST once I get some time to fix the windows paths bugs that are preventing me from merging (fwiw there are something like 23k unit tests, and 5 or 6 of them are failing for the same reason. I just haven't had time to fix them)

**Comment by fidian** [comment]
I ran the tests on Linux and found no problems. Do you have a way to simulate a Windows environment, such as using `path.win32` by default or by mocking a `require()`? It seems like this would be useful to do so you are not required to run the tests on every operating system in order to prove that a release would work.

**Comment by jonschlinkert** [comment]
> I ran the tests on Linux and found no problems.

Yeah, they all pass on Linish. 

> Do you have a way to simulate a Windows environment, such as using path.win32 by default or by mocking a require()

That's a great idea, I'd definitely take a pr for it - even it it's just to get it started - if you're interested in tackling it.

**Comment by jonschlinkert** [comment]
Closing based on age, and 3.0 was released so this should be possible now.

**Comment by devongovett** [comment]
Added preliminary support for this to `nanomatch`: https://github.com/micromatch/nanomatch/pull/4. If that is merged, I'll also update `micromatch` and `extglob`.

**Comment by devongovett** [comment]
Added https://github.com/micromatch/extglob/pull/9 and https://github.com/micromatch/micromatch/pull/105.
