### ISSUE TITLE
double slash in the pattern

### ISSUE THREAD

**Issue by kt3k** [micromatch/micromatch#89]
I found this difference between micromatch and minimatch:

```
> require('micromatch').isMatch('foo/baz.md', 'foo//baz.md')
false
> require('minimatch')('foo/baz.md', 'foo//baz.md')
true
```

Is this intended or not?

---
I'm using the pattern like `source/{,!(node_modules)}/!(README).md` in my script, and this expands to `source//!(README).md` and `source/!(node_modules)/!(README).md`. I use chokidar and gulp with this pattern and both seem working on different paths because of the above difference.

**Comment by jonschlinkert** [comment]
is this against master or dev?

**Comment by kt3k** [comment]
Thanks for the quick response!

After doing some checks with Bash like the below, I agree with you that both `mm.isMatch('foo//baz.md', 'foo/baz.md')` and `mm.isMatch('foo/baz.md', 'foo//baz.md')` should be `false`.

```
$ cat test.sh
[[ "foo/bar.md" = foo/*.md ]]; echo $?
[[ "foo/bar.md" = foo//bar.md ]]; echo $?
[[ "foo//bar.md" = foo/bar.md ]]; echo $?
$ ./test.sh
0
1
1
```

`micromatch` seems more conformant to Bash in these cases. 👍
