### ISSUE TITLE
3.0.0 regressions? please let us know!

### ISSUE THREAD

**Issue by jonschlinkert** [micromatch/micromatch#93]
If you experience regressions with upgrading to 3.0, please let us know, we're here to help!

**Comment by yvele** [comment]
`3.0.0` is a major release.. but where is the changelog? What exactly is supposed to be breaking?

https://github.com/micromatch/micromatch/releases

![image](https://cloud.githubusercontent.com/assets/4225430/26676760/6bd3f96e-46c9-11e7-913a-cee138af669d.png)

https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md

![image](https://cloud.githubusercontent.com/assets/4225430/26676765/77591ad0-46c9-11e7-9170-53391a1f03cd.png)

**Comment by jonschlinkert** [comment]
Why are you assuming something is supposed to be breaking? Feel free to review the commits and submit a pr with an update to the change log

**Comment by yvele** [comment]
@jonschlinkert I supposed you are following [semver](http://semver.org/) standard like all other libraries. If not, I think you should follow [semver](http://semver.org/) standard 😉 

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>  1. **MAJOR version** when you make **incompatible API changes**,
>  2. MINOR version when you add functionality in a backwards-compatible manner, and
>  3. PATCH version when you make backwards-compatible bug fixes.

MAJOR version is supposed to be breaking and to be huge and **deserve a changelog entry**.. at least one line.

When a developer manage a huge (or many huge) repos, and is updating dependencies.. when he sees a MAJOR increment, that means a bit of work trying to understand WHAT exactly is changing..
