### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by electerious** [micromatch/micromatch#95]
I updated micromatch from 2.3.11 to 3.0.3. My tests are running fine on macOS, but are failing on Windows: https://ci.appveyor.com/project/electerious/rosid/build/1.0.55/job/xd2am7ys0vfx80p3

There seems to be no changelog or release notes, so I'm not sure if I need to change anything on my side.

The error:

```
1) copy() should copy a directory without ignored files:
     Error: no parsers registered for: "]*.{h"
      at parse (node_modules\snapdragon\lib\parser.js:473:15)
      at Parser.parse (node_modules\snapdragon\lib\parser.js:477:24)
      at Snapdragon.parse (node_modules\snapdragon\index.js:122:28)
      at Snapdragon.<anonymous> (node_modules\micromatch\node_modules\braces\lib\braces.js:37:45)
      at Braces.parse (node_modules\micromatch\node_modules\braces\lib\braces.js:74:26)
      at Braces.optimize (node_modules\micromatch\node_modules\braces\lib\braces.js:105:18)
      at create (node_modules\micromatch\node_modules\braces\index.js:141:15)
      at memoize (node_modules\micromatch\node_modules\braces\index.js:293:13)
      at Function.braces.create (node_modules\micromatch\node_modules\braces\index.js:161:10)
      at braces (node_modules\micromatch\node_modules\braces\index.js:54:18)
      at expand (node_modules\micromatch\index.js:592:12)
      at memoize (node_modules\micromatch\index.js:829:13)
      at Function.micromatch.braces (node_modules\micromatch\index.js:595:10)
      at node_modules\micromatch\index.js:654:26
      at memoize (node_modules\micromatch\index.js:829:13)
      at Function.micromatch.create (node_modules\micromatch\index.js:649:10)
      at makeRe (node_modules\micromatch\index.js:544:29)
      at memoize (node_modules\micromatch\index.js:829:13)
      at Function.micromatch.makeRe (node_modules\micromatch\index.js:561:10)
      at matcher (node_modules\micromatch\index.js:486:23)
      at memoize (node_modules\micromatch\index.js:829:13)
      at Function.micromatch.isMatch (node_modules\micromatch\index.js:170:17)
      at Function.micromatch.any (node_modules\micromatch\index.js:276:20)
      at filter (src\copy.js:9:1462)
      at startCopy (node_modules\fs-extra\lib\copy\ncp.js:44:14)
      at ncp (node_modules\fs-extra\lib\copy\ncp.js:33:3)
      at pathExists (node_modules\fs-extra\lib\copy\copy.js:45:29)
      at fn.apply.then.r (node_modules\universalify\index.js:23:46)
```

How I use micromatch:

https://github.com/electerious/Rosid/blob/master/src/copy.js#L62

The test that fails:

https://github.com/electerious/Rosid/blob/master/test/copy.js#L16

Simplified code:

```js
mm.any(filePath, [
	'**/CVS',
	'**/.git',
	'**/.svn',
	'**/.hg',
	'**/.lock-wscript',
	'**/.wafpickle-N',
	'[^_]*.{html,ejs}*',
	'**/*.css'
])
```

Let me know if there's anything else I can provide to make debugging easier.

**Comment by electerious** [comment]
The error `Error: no parsers registered for: "]*.{h"` seems to refer to the `[^_]*.{html,ejs}*` pattern.

**Comment by jonschlinkert** [comment]
> There seems to be no changelog or release notes

here are the [release notes](https://github.com/micromatch/micromatch/pull/76). There shouldn't be changes

There are bound to be new matching edge cases since the parser was re-written from the ground up.  But generally, they should be pretty easy to fix now, as long as I have enough information to debg. 

> so I'm not sure if I need to change anything on my side.

Nope, you found a bug, thanks for reporting it.

> Let me know if there's anything else I can provide to make debugging easier.

The thing that would help me most is if you could narrow down the failure to a specific pattern, or patterns. 

Fwiw, my goal is to make matching on windows as consistent as any other platform and I've tried to test on windows as much as possible.  I used windows for 20 years, so I'm really familiar, but I work on a mac now so there isn't as much rigor from a practical standpoint.  any feedback helps! thanks!

**Comment by jonschlinkert** [comment]
hmm, could you do me a favor and try these? (no worries if you don't have a chance)

```
'*/[^_]*.{html,ejs}*'
'a/[^_]*.{html,ejs}*'
'[^_]*.{html,ejs}'
'[^_]*.html'
```

**Comment by electerious** [comment]
Will try your patterns.

> edit: one more thing... what does glob-escape do? That seems like a potentially bad idea (given that backslashes are path separators on windows and are exclusively reserved for escaping), but I haven't looked at it yet.

It's because of this issue I had: https://www.sternglas.de/shop/

> also, is there a reason you're using regex instead of a negation glob (like !_*.{html,ejs})?

Not really. I wasn't aware I can do it this way. I will check if it makes a difference.

**Comment by electerious** [comment]
`!_*.{html,ejs}` 1) 4)
`*/[^_]*.{html,ejs}*` 1)
`a/[^_]*.{html,ejs}*` 1)
`[^_]*.{html,ejs}` 2)
`[^_]*.html` + `[^_]*.ejs` 3)

1) No error, but pattern has a different behavior and my tests are failing because of this: https://ci.appveyor.com/project/electerious/rosid/build/1.0.72/job/srfjb4x7p6t1l5r5
2) Throws `no parsers registered for: "]*.{h"`.
3) Works on macOS, but fails on windows because of a different behavior: https://ci.appveyor.com/project/electerious/rosid/build/1.0.74/job/17hbg0e822r8pdw3
4) Could be a workaround, but `!_*.{html,ejs}` seems to be different to what `!_*.{html,ejs}` does.

I also tested the impact of `glob-escape`. Disabling it doesn't help: https://ci.appveyor.com/project/electerious/rosid/build/job/7e6u6ma2kf90pocv

**Comment by jonschlinkert** [comment]
thanks! the parser error is a bug. But I know there are negation character classes being tested so I'll look into it and get it fixed.

> Could be a workaround

try using `!(_*.{html,ejs})`, and see what that produces.

**Comment by jonschlinkert** [comment]
> Throws `no parsers registered for: "]*.{h".`

I'm not able to reproduce this error. If you could log out the actual paths that are being created in your build and paste them here that would be helpful.

**Comment by litmit** [comment]
I don't know its related bug or not but try to report it here. Following code :
```js
const mm = require("micromatch");
var pattern = "*[\\[\\]\\{\\}]*";  
console.log(pattern);
console.log(mm.match(["*", "aa", "]"], pattern));
```
cause exception:
```
*[\[\]\{\}]*
C:\test\node_modules\micromatch\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]*"
    at parse (C:\test\node_modules\micromatch\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\test\node_modules\micromatch\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\test\node_modules\micromatch\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\test\node_modules\micromatch\node_modules\braces\lib\braces.js:37:45)
    at Braces.parse (C:\test\node_modules\micromatch\node_modules\braces\lib\braces.js:74:26)
    at Braces.optimize (C:\test\node_modules\micromatch\node_modules\braces\lib\braces.js:105:18)
    at create (C:\test\node_modules\micromatch\node_modules\braces\index.js:141:15)
    at memoize (C:\test\node_modules\micromatch\node_modules\braces\index.js:293:13)
    at Function.braces.create (C:\test\node_modules\micromatch\node_modules\braces\index.js:161:10)
    at braces (C:\test\node_modules\micromatch\node_modules\braces\index.js:54:18)
```

**Comment by jonschlinkert** [comment]
yeah, i think it's the same bug. thanks, that gives me an idea of what's causing it.

**Comment by evilebottnawi** [comment]
@jonschlinkert https://github.com/stylelint/stylelint/pull/2597 we also have troubles on windows, on linux all works fine

**Comment by jonschlinkert** [comment]
yep I've [made comments on that issue](https://github.com/stylelint/stylelint/pull/2597#issuecomment-305768487). 

fwiw I spent quite a bit of time trying to get the unit tests to run to log out the patterns, but didn't have any more time to spend on it. I'm strapped for time atm, but I'd like to get it fixed. If someone could copy/paste into this issue specifically which patterns and file paths that aren't being matched properly on windows versus linux that would help a great deal. Also, if the patterns are being modified at all, like with `path.join()` or something, please also provide the modified patterns.

**Comment by jonschlinkert** [comment]
@litmit since you commented here, I'm assuming you are on windows? Just want to make sure.

**Comment by evilebottnawi** [comment]
@jonschlinkert i tried to update to latest version and tests still failed, i will try to find time today to investigate which patterns don't work in our test, thanks!

**Comment by litmit** [comment]
@jonschlinkert Yes, I'm using Windows.

**Comment by evilebottnawi** [comment]
@jonschlinkert Some information:
list:
```shell
C:\Users\IEUser\stylelint\stylelint\lib\__tests__\fixtures\invalid-hex.css
```
patterns:
```shell
  [ '**/node_modules/**',
      '**/bower_components/**',
      'C:\\Users\\IEUser\\stylelint\\stylelint\\lib\\__tests__\\fixtures\\**\\invalid-hex.css' ]
```
In v2 it is works as ignore, now not ignore.

**Comment by evilebottnawi** [comment]
Other example:
List:
```shell
C:\Users\IEUser\stylelint\stylelint\lib\__tests__\fixtures\standaloneNoParsing\syntax-error-ignored.scss
```
Patterns:
```shell
[ '**/node_modules/**',
      '**/bower_components/**',
      'C:\\Users\\IEUser\\stylelint\\stylelint\\**\\*.scss' ]
```
Seems should be ignored, but not.

**Comment by jonschlinkert** [comment]
@evilebottnawi thanks! that helps. 

Here is what's happening. The patterns are being corrupted by the `path` module. 

In particular, when the pattern `**/*.scss` is joined to the directory, the slashes are converted to backslashes, which escapes the wildcards. 

The [backslashes section in the readme](https://github.com/micromatch/micromatch#backslashes) explains this in more detail.

**Comment by electerious** [comment]
What is the best way to join a path/glob pattern without causing issues? I'm currently using `path.join` to prepend a user defined folder to every glob pattern:

```js
path.join(baseFolderDefinedByUser, globPattern)
```

Joining manually with `path.sep` could be a solution. Are there any edge-cases I forgot to think about?

**Comment by jonschlinkert** [comment]
well, since a glob pattern is a type of regular expression and not a file path, it should always have forward slashes as path separators. In other words, using `path.sep` is actually what's causing the problem.

> What is the best way to join a path/glob pattern without causing issues?

Maybe try using`path.posix` to ensure that posix slashes are always used when joining glob patterns. 

```js
var path = require('path').posix;
```

Or, maybe consider keeping the globs as they are and testing against relative paths. that might be naive, I haven't looked at that code closely enough.

**Comment by electerious** [comment]
@jonschlinkert Thanks for the clarification.

I know remember why I used [glob-escape](https://www.npmjs.com/package/glob-escape). This lets me use a path inside a glob pattern (on windows). The only issue on my side was that I used `path.join` to concat the escaped path with the glob pattern. This created a new, unescaped backslash.

**Comment by megamindbrian** [comment]
Is there a solution for this?  I've tried both chokidar and glob-watcher and they both give me this error.  I assume it's something to do with version numbers.

**Comment by jonschlinkert** [comment]
Can you clarify? This is a closed issue, which means it was solved.

**Comment by megamindbrian** [comment]
@jonschlinkert I ran npm update today and when I use watch('**/*.ipynb') I get this error:
https://github.com/here-be/snapdragon/issues/11
