### ISSUE TITLE
basename: true and unixify: true breaks .not()

### ISSUE THREAD

**Issue by rogierschouten** [micromatch/micromatch#96]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

``` shell
$ node
> let mm = require("micromatch")
undefined
> mm.not(["C:\\bla\\bar.xml"], ["*.xml"], {basename: true, unixify: true})
[ 'C:\\bla\\bar.xml' ]
> mm.not(["C:\\bla\\bar.xml"], ["*.xml"], {basename: true, unixify: false})
[]
> mm.not(["C:\\bla\\bar.xml"], ["**/*.xml"], {basename: false, unixify: true})
[ 'C:\\bla\\bar.xml' ]
> mm.not(["C:\\bla\\bar.xml"], ["**/*.xml"], {basename: false, unixify: false})
[]
>
```
…

## What is happening (but shouldn't):

Specifying basename: true and unixify: true  on Windows breaks the .not() function (inverts its logic)

…

## What should be happening instead?

Specifying basename: true and unixify: true  on Windows does not break the .not() function (inverts its logic)

…

**Comment by doowb** [comment]
I have a fix for this (tested on mac and windows). I'll submit a PR in a bit.
